#!/usr/bin/env python3
"""gen_build_index.py — the generated build index for a flat memory tree (memory-tree kit 1.5).

    python tools/memory-tree/gen_build_index.py --check      # drift gate (writes nothing)
    python tools/memory-tree/gen_build_index.py --write      # (re)render every artifact
    python tools/memory-tree/gen_build_index.py --selftest    # fixtures, in a temp dir

It replaces the retired directory-listing generator. A listing carried paths, which git already
prints better; this carries STATUS, which git does not — and a build's status is a PURE FUNCTION of
its units' statuses, so nothing here is authored and nothing rots.

THREE SOURCES, NOTHING ELSE
  * each build's README front matter (slug node opened streams roster [status])
  * every `**Status:**` header under that build's spec/, at any depth
  * for the ROSTER only, every tracked file under the memory root EXCEPT this field's own outputs —
    the build's own README and the generated index and shards. `ids` is therefore an OUTPUT, not a
    source: `--write` overwrites whatever was authored there.
No git history and no mtimes. A source the renderer does not read cannot make the render drift; a
source the renderer WRITES must not also be read, or a wrong value defends itself forever.

ONE SOURCE OF TRUTH PER BUILD
  * any spec carries a parseable header -> the status is DERIVED, and an authored `status:` is an
    ERROR (two answers to one question is the drift this file exists to remove);
  * no spec carries one -> `status:` is REQUIRED, and its absence is a named error.
Three builds in the originating corpus are grandfathered recordings with no status header at all;
every plausible default for them was wrong, so the fallback is explicit and gated instead.

THE THREE BLIND SPOTS THIS CLOSES (each armed in --selftest)
  1. a README with no marker PAIR used to leave the universe silently -> named error;
  2. an orphaned generated file was permanent and invisible -> reported, and removed by --write,
     BOUNDED to a `ledger/<YYYY-MM>.md` name; anything else in ledger/ is reported and left alone,
     because a generator that deletes inside the memory tree on its own authority is a data-loss path;
  3. an absent README killed both modes with a traceback -> named error, never a stack.
"""
from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys
import tempfile

RECORD_KINDS = ("spec", "build", "reviews", "prompts")
MARK_OPEN = "<!-- gen:build-index -->"
MARK_CLOSE = "<!-- /gen:build-index -->"
# The stamped header names THIS install's prefix, derived from the module's own location rather
# than spelled. It is written INTO the adopter's generated artifacts and committed there, so a
# hardcoded prefix does not merely mislead — it lands a dead path in their tree, and the byte-compare
# that guards these files happily agrees with it. `kit_rel()` falls back to the bare kit name when the
# module sits outside the resolved root (a test fixture, an odd checkout); the header is a pointer,
# never a gate input.
def kit_rel() -> str:
    here = pathlib.Path(__file__).resolve().parent
    for anc in [here] + list(here.parents):
        if (anc / ".git").exists():
            try:
                return here.relative_to(anc).as_posix()
            except ValueError:
                break
    return here.name


GEN_HEADER = (
    f"<!-- generated by {kit_rel()}/gen_build_index.py --write — do not hand-edit -->"
)

STATUS_TOKENS = ("OPEN", "SPECCED", "INPROGRESS", "BLOCKED", "DEFERRED", "CLOSED", "WONTDO")
TERMINAL = ("CLOSED", "WONTDO")
# Precedence for the derived status, most-live first. A build is as live as its liveliest unit.
PRECEDENCE = ("INPROGRESS", "BLOCKED", "OPEN", "SPECCED", "DEFERRED")

HDR_RE = re.compile(
    r"^\*\*Status:\*\* (?P<token>" + "|".join(STATUS_TOKENS) + r")"
    r" · rev-(?P<rev>\d+) · (?P<date>\d{4}-\d{2}-\d{2}) · node (?P<node>[a-z])"
    r" · Tier-(?P<tier>[12]) · base (?P<base>[0-9a-f]{8,})"
)
H1_RE = re.compile(r"^#\s+(?P<id>[A-Za-z0-9][A-Za-z0-9-]*)\s+—\s+(?P<title>.+?)\s*$")
SHARD_RE = re.compile(r"^\d{4}-\d{2}\.md$")
REQUIRED_KEYS = ("slug", "node", "opened", "streams", "roster", "ids")


class Problem(Exception):
    """A named, user-facing failure. Never a traceback: blind spot 3."""


# --------------------------------------------------------------------------------------- plumbing
def run(*argv: str, cwd: str | None = None) -> str:
    return subprocess.run(argv, cwd=cwd, capture_output=True, text=True, check=True).stdout


def read_text(path: str) -> str:
    # Bytes in, decode, normalise CR. Windows checkouts hand back CRLF and every comparison below
    # would then differ on every line — the exact green-by-accident shape a byte gate must not have.
    with open(path, "rb") as fh:
        return fh.read().decode("utf-8").replace("\r\n", "\n")


def write_text(path: str, text: str) -> None:
    # BYTES, never write_text(): on Windows the text mode would re-expand \n to \r\n and the very
    # next --check would report the file this call just wrote as stale.
    os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(path) else None
    with open(path, "wb") as fh:
        fh.write(text.encode("utf-8"))


def load_conf(root: str) -> dict:
    conf = {"MEMORY_ROOT": "memory", "DISCIPLINES": "", "FAMILIES": ""}
    path = os.path.join(root, ".memory-tree.conf")
    if os.path.isfile(path):
        for line in read_text(path).split("\n"):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            conf[k.strip()] = v.strip().strip('"').strip("'")
    return conf


def unfenced_lines(text: str):
    """Yield (lineno, line) for every line OUTSIDE a fenced block, then the open fence's line.

    The final yield is `(opened_at, None)` when the document ends inside a fence, and nothing when it
    does not. A caller that only wants the text ignores it; a caller that must REFUSE a document it
    could not fully read needs it, and no reader in either kit had it — the shell `_unfenced` and this
    module's own generator both end silently with the fence still open, dropping every later line at
    exit 0. That is invisible by construction: a fence opened near the top of a row document hides
    every duplicate below it, and hiding duplicates is what the check that reads this exists to stop.
    """
    fence = ""
    opened_at = 0
    for n, line in enumerate(text.split("\n"), 1):
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            mark = "```" if stripped.startswith("```") else "~~~"
            if not fence:
                fence, opened_at = mark, n
                continue
            # Only the marker that OPENED the fence closes it: a ``` line inside a ~~~ block is
            # content, not a toggle.
            if mark == fence:
                fence = ""
                continue
        if not fence:
            yield n, line
    if fence:
        yield opened_at, None


def unfenced(text: str):
    """The text-only view, kept as the one fence machine's façade rather than a second copy."""
    for _n, line in unfenced_lines(text):
        if line is not None:
            yield line


# ----------------------------------------------------------------------------------------- parsing
def parse_front_matter(path: str, slug: str) -> dict:
    """Front matter opens at LINE 1 and nowhere else.

    `---` is also a markdown horizontal rule, and one already separates the two merged halves of a
    real build README in the originating corpus. A parser that scanned for the first two `---`
    anywhere would swallow that whole half as front matter.
    """
    lines = read_text(path).split("\n")
    if not lines or lines[0].strip() != "---":
        raise Problem(f"{path}: no front matter — line 1 must be '---' (build '{slug}')")
    fm: dict = {}
    end = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
        if not line.strip():
            continue
        if line[:1].isspace():
            raise Problem(
                f"{path}:{i + 1}: front-matter key is indented — keys live at COLUMN 0, and an "
                f"indented key is silently dropped by every simple parser"
            )
        if ":" not in line:
            raise Problem(f"{path}:{i + 1}: front-matter line is not 'key: value'")
        k, _, v = line.partition(":")
        fm[k.strip()] = v.strip()
    if end is None:
        raise Problem(f"{path}: front matter opened at line 1 but never closed with '---'")
    missing = [k for k in REQUIRED_KEYS if k not in fm]
    if missing:
        raise Problem(f"{path}: front matter missing required key(s): {', '.join(missing)}")
    if fm["slug"] != slug:
        raise Problem(f"{path}: front matter slug '{fm['slug']}' != folder name '{slug}'")
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", fm["opened"]):
        raise Problem(f"{path}: opened '{fm['opened']}' is not a YYYY-MM-DD date")
    if "status" in fm and fm["status"] not in STATUS_TOKENS:
        raise Problem(f"{path}: status '{fm['status']}' is not one of {' '.join(STATUS_TOKENS)}")
    return fm


def parse_spec(path: str) -> dict | None:
    """Return the unit record, or None when the file carries no parseable status header.

    A grandfathered recording legitimately has none; check 12 already rejects a post-cutoff spec
    that is missing one, so this file never has to defend against a malformed header.
    """
    body = list(unfenced(read_text(path)))
    hdr = None
    for line in body[:5]:
        m = HDR_RE.match(line)
        if m:
            hdr = m
            break
    if hdr is None:
        return None
    unit_id, title = os.path.basename(path)[:-3], ""
    for line in body[:5]:
        m = H1_RE.match(line)
        if m:
            unit_id, title = m.group("id"), m.group("title")
            break
    return {
        "path": path,
        "id": unit_id,
        "title": title,
        "status": hdr.group("token"),
        "rev": hdr.group("rev"),
        "date": hdr.group("date"),
    }


def derive_status(units: list, fm: dict, readme: str) -> str:
    parsed = [u for u in units if u]
    if not parsed:
        if "status" not in fm:
            raise Problem(
                f"{readme}: no spec under this build carries a parseable **Status:** header, so the "
                f"build status cannot be derived — declare it explicitly with a 'status:' front-matter key"
            )
        return fm["status"]
    if "status" in fm:
        raise Problem(
            f"{readme}: front matter declares 'status: {fm['status']}' but {len(parsed)} spec(s) "
            f"carry a status header — the build status is DERIVED from them, and two answers to one "
            f"question is exactly the drift this index removes. Delete the 'status:' key."
        )
    seen = {u["status"] for u in parsed}
    for token in PRECEDENCE:
        if token in seen:
            return token
    return "WONTDO" if seen == {"WONTDO"} else "CLOSED"


# ----------------------------------------------------------------------------------- roster scanning
def _roster_sort_key(i: str):
    """Family, then NUMERIC sequence. Lexical order puts `-10` before `-2`, which reads as data loss
    to anyone scanning the rendered list for the newest id."""
    return (i.split("-", 1)[0], int(i.rsplit("-", 1)[1]))


def rosters(root: str, tracked: list, m: str, families: set) -> dict:
    """slug -> sorted ids belonging to that build, from the id's own slug component.

    An id spells its build: family-slug-sequence. So a build's roster needs no side table and no
    anchor grammar — only the declared family alternation, which this module already loads. The
    sequence must be all DIGITS: revision-suffixed anchors (`-6q`) are amendments to a decision, not
    ids of their own, and admitting them multiplied one build's roster from 8 to 38.

    THE READ SET EXCLUDES THIS FIELD'S OWN OUTPUTS. A build's README is skipped for its OWN slug, and
    the generated index and shards are skipped entirely, because all three are rendered FROM the
    value being derived. A derivation that reads its own output cannot correct a wrong value — it
    republishes it forever, and every gate agrees, because a fresh render reproduces it exactly. That
    is the defect this change exists to remove, so it must not be reintroduced by the fix.
    """
    fam = "|".join(sorted(re.escape(f) for f in families))
    if not fam:
        raise Problem("build-index: FAMILIES is empty, so no id can be recognised and every roster "
                      "would render empty — which is also what a clean corpus looks like")
    id_re = re.compile(r"\b(?:" + fam + r")-([A-Za-z0-9]+)-\d+\b")
    out: dict = {}
    for p in tracked:
        if p == f"{m}/LIVE.md" or p.startswith(f"{m}/ledger/"):
            continue
        try:
            text = read_text(os.path.join(root, p))
        except Problem:
            continue
        for mm in id_re.finditer(text):
            slug = mm.group(1)
            if p == f"{m}/builds/{slug}/README.md":
                continue
            out.setdefault(slug, set()).add(mm.group(0))
    return {s: sorted(v, key=_roster_sort_key) for s, v in out.items()}


# --------------------------------------------------------------------------------------- collecting
def collect(root: str, conf: dict) -> list:
    m = conf["MEMORY_ROOT"]
    tracked = [p for p in run("git", "ls-files", "--", m + "/", cwd=root).split("\n") if p]
    slugs = sorted({p.split("/")[2] for p in tracked if p.startswith(m + "/builds/") and p.count("/") >= 3})
    disciplines = set(conf["DISCIPLINES"].split())
    families = {pair.split(":")[1] for pair in conf["FAMILIES"].split() if ":" in pair}
    # Two granularities, as the hygiene engine's own guard does it. The PRECONDITION asks whether the
    # scan recognised anything at all; the per-build POPULATION asks whether this build did. Without
    # the first, a families list bound to the wrong tree renders every roster empty — and an empty
    # classification is exactly what a clean corpus yields, so the failure would look like success.
    roster_by_slug = rosters(root, tracked, m, families)
    # NO EMPTINESS PRECONDITION HERE, deliberately. The wrong-root class says an unrecognising
    # grammar yields the same empty result a clean corpus does, so a guard is wanted — but every
    # signal available HERE is one this function derives from the same conf, which makes the
    # assertion a tautology (the repo's assertion-between-two-derived-values class). Build count
    # fails on a sparse tree; spec-file existence fails too, because a legacy recording legitimately
    # carries no id. The guard that actually holds is INDEPENDENT and already runs below: every
    # build's authored `roster:` value must be a declared family, so a FAMILIES list bound to the
    # wrong tree reds there, by name, before any roster is rendered.
    builds = []
    for slug in slugs:
        readme = f"{m}/builds/{slug}/README.md"
        if readme not in tracked:
            raise Problem(
                f"{m}/builds/{slug}/: no tracked README.md — a build with no front matter cannot be "
                f"indexed, and an unindexed build is a silent departure from the universe"
            )
        fm = parse_front_matter(os.path.join(root, readme), slug)
        for value in fm["streams"].split("+"):
            if disciplines and value.strip() not in disciplines:
                raise Problem(f"{readme}: streams value '{value.strip()}' is outside the DISCIPLINES enum")
        for value in fm["roster"].split("+"):
            if families and value.strip() not in families:
                raise Problem(f"{readme}: roster value '{value.strip()}' is outside the FAMILIES set")
        specs = sorted(p for p in tracked if p.startswith(f"{m}/builds/{slug}/spec/") and p.endswith(".md"))
        units = [parse_spec(os.path.join(root, p)) for p in specs]
        # BOOTSTRAP, not failure. A build whose ids appear nowhere but its own README is young, not
        # broken, and there is nothing to correct the authored value against — so it stands. The
        # anti-self-reference property still holds where it can bite: the moment any independent
        # source names the id, the derivation takes over and a wrong authored value loses. Global
        # emptiness is the dangerous case, and the precondition above owns it.
        roster = roster_by_slug.get(slug) or [i for i in fm["ids"].split() if i]
        # Which record folders this build actually HAS. Authored as prose in 17 READMEs and wrong
        # in 15 of them: the sentence is written when a build opens, predicting the folders it will
        # grow, and nothing revisits it. Seven claim a build/ that was never created.
        kinds = [k for k in RECORD_KINDS
                 if any(t.startswith(f"{m}/builds/{slug}/{k}/") for t in tracked)]
        builds.append(
            {
                "slug": slug,
                "readme": readme,
                "fm": fm,
                "roster": roster,
                "kinds": kinds,
                "units": [u for u in units if u],
                "status": derive_status(units, fm, readme),
            }
        )
    return builds


# ---------------------------------------------------------------------------------------- rendering
def render_region(build: dict) -> str:
    fm = build["fm"]
    out = [
        MARK_OPEN,
        # `unit(s)` and `ids` answer DIFFERENT questions and are deliberately not reconciled: a unit
        # is a spec carrying a status header, a roster member is an id that exists in the record.
        # aUnmannedHelm is 7 and 10 because three of its ids never got a spec. Rendering them as one
        # number would re-create, inverted, the defect this derivation removes.
        f"**Build status:** {build['status']} · {len(build['units'])} unit(s) · node {fm['node']} · "
        f"opened {fm['opened']} · streams {fm['streams']} · ids {' '.join(build['roster'])}",
        "",
    ]
    if build["units"]:
        out += ["| Unit | Status | Rev | Last change |", "|---|---|---|---|"]
        for u in sorted(build["units"], key=lambda x: x["path"]):
            rel = u["path"].split(f"/builds/{build['slug']}/", 1)[1]
            label = f"{u['id']} — {u['title']}" if u["title"] else u["id"]
            out.append(f"| [{label}]({rel}) | {u['status']} | rev-{u['rev']} | {u['date']} |")
    else:
        out.append("*No spec under this build carries a status header; the status above is declared "
                   "in the front matter.*")
    if build["kinds"]:
        ks = [f"`{k}/`" for k in build["kinds"]]
        joined = ks[0] if len(ks) == 1 else ", ".join(ks[:-1]) + " and " + ks[-1]
        out += ["", f"Records live under {joined}."]
    out.append(MARK_CLOSE)
    return "\n".join(out)


RECORDS_SENTENCE = re.compile(r"Records live under [^.]*\.[ ]?")


def strip_records_sentence(readme_text: str, readme: str) -> str:
    """Remove the AUTHORED folder-claim sentence from the body, OUTSIDE the marker pair.

    SENTENCE-scoped, never line-scoped, and that distinction is the whole safety property.
    Measured over the corpus: in 17 of 17 carriers the sentence ENDS mid-line and the next
    sentence begins on the same line, wrapping onward —

        Records live under `spec/`, `build/` and `reviews/`. The table below is
        GENERATED from the status header of every spec in this folder ...

    so deleting the LINE destroys "The table below is" in every file it touches and orphans the
    line after it. The first draft bounded the removal to "a single anchored LINE" and called that
    a safety property; it was a description of the wrong unit, and every acceptance criterion it
    carried would have passed while prose was eaten.

    A second match outside the region is a REFUSAL, not a second removal: two matches mean the
    anchor is not identifying what it was reasoned about.
    """
    lines = readme_text.split("\n")
    opens = [i for i, l in enumerate(lines) if l.rstrip("\r") == MARK_OPEN]
    end = opens[0] if opens else len(lines)
    hits = [i for i in range(end) if RECORDS_SENTENCE.search(lines[i])]
    if not hits:
        return readme_text
    if len(hits) > 1:
        where = ", ".join(str(i + 1) for i in hits)
        raise Problem(f"{readme}: the folder-claim sentence appears {len(hits)} times outside the "
                      f"generated region, at lines {where} — the anchor is not identifying one "
                      f"sentence, so nothing is removed")
    i = hits[0]
    rest = RECORDS_SENTENCE.sub("", lines[i], count=1)
    # Only drop the physical line when the sentence WAS the whole of it; otherwise the surviving
    # text stays exactly where the author put it.
    if rest.strip():
        lines[i] = rest
    else:
        del lines[i]
    return "\n".join(lines)


def apply_front_matter_ids(readme_text: str, roster: list, readme: str) -> str:
    """Rewrite the front matter's `ids:` line from the roster, in place.

    Bounded exactly like `apply_region`: only the ONE line whose key is `ids` inside the front-matter
    block is touched, and the block ends at the first closing `---`. `parse_front_matter` has already
    proved the block opens at line 1 and closes, so this walk cannot run away; it still refuses
    rather than guessing if the key is absent, because writing a key that was never there would make
    this function a scaffolder, which it is not.
    """
    lines = readme_text.split("\n")
    want = ("ids: " + " ".join(roster)).rstrip()
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            break
        if line.startswith("ids:"):
            lines[i] = want
            return "\n".join(lines)
    raise Problem(f"{readme}: front matter has no 'ids:' line to rewrite")


def apply_region(readme_text: str, region: str, readme: str) -> str:
    """Replace the marked slice EXACTLY. Never a regex substitution over the whole file: this
    generator owns a region inside an AUTHORED file, and getting it wrong eats prose."""
    lines = readme_text.split("\n")
    # COLUMN 0, EXACT EQUALITY after one trailing CR — the contract the three awk readers in the
    # unattended kit already enforce. `.strip()` was permissive AND mutating: it accepted an
    # indented marker and a marker with trailing whitespace (two spaces is a Markdown hard break,
    # so an authored construct), then re-emitted the bare marker — silently rewriting a line the
    # author wrote, in a file they ran this tool over for another reason. Refusing is the only
    # reading that cannot edit prose behind the author.
    def _is(line, mark):
        return line.rstrip("\r") == mark
    opens = [i for i, l in enumerate(lines) if _is(l, MARK_OPEN)]
    closes = [i for i, l in enumerate(lines) if _is(l, MARK_CLOSE)]
    if not opens and not closes:
        raise Problem(f"{readme}: no '{MARK_OPEN}' / '{MARK_CLOSE}' marker pair — the generated "
                      f"region has nowhere to go, and a README without one leaves the index silently")
    if len(opens) != 1 or len(closes) != 1:
        raise Problem(f"{readme}: expected exactly one marker pair, found {len(opens)} open and "
                      f"{len(closes)} close")
    if closes[0] < opens[0]:
        raise Problem(f"{readme}: the closing marker precedes the opening one")
    return "\n".join(lines[: opens[0]] + region.split("\n") + lines[closes[0] + 1 :])


def render_live(builds: list, m: str) -> str:
    live = [b for b in builds if b["status"] not in TERMINAL]
    out = [
        GEN_HEADER,
        f"# {m}/LIVE.md — builds with at least one non-terminal unit",
        "",
        "Derived, never authored: a build leaves this file when every one of its units reaches a",
        "terminal status. Nothing here is edited by hand.",
        "",
    ]
    if live:
        # A COUNT, not the list. This file is in check 7's entry-budget population and the build
        # README's region is not, so the full roster renders there and a bounded number renders here:
        # a ten-id row measured 316 chars against a 300-char cap, on a file with no slack.
        out += ["| Build | Status | Node | Opened | Streams | Ids (n) |", "|---|---|---|---|---|---|"]
        for b in live:
            fm = b["fm"]
            out.append(
                f"| [{b['slug']}](builds/{b['slug']}/README.md) | {b['status']} | {fm['node']} | "
                f"{fm['opened']} | {fm['streams']} | {len(b['roster'])} |"
            )
    else:
        out.append("*No live build.*")
    return "\n".join(out) + "\n"


def render_shards(builds: list, m: str) -> dict:
    months: dict = {}
    for b in builds:
        months.setdefault(b["fm"]["opened"][:7], []).append(b)
    out = {}
    for month, rows in months.items():
        body = [
            GEN_HEADER,
            f"# {m}/ledger/{month}.md — builds opened in {month}",
            "",
            "Frozen once the month passes: its inputs stop changing, so no rotation rule is needed.",
            "",
            "| Build | Status | Node | Streams | Ids (n) |",
            "|---|---|---|---|---|",
        ]
        for b in sorted(rows, key=lambda x: x["slug"]):
            fm = b["fm"]
            body.append(
                f"| [{b['slug']}](../builds/{b['slug']}/README.md) | {b['status']} | {fm['node']} | "
                f"{fm['streams']} | {len(b['roster'])} |"
            )
        out[f"{m}/ledger/{month}.md"] = "\n".join(body) + "\n"
    return out


def plan(root: str, conf: dict) -> tuple:
    """Return (artifacts, orphans, unmanaged) — the whole render, computed without touching disk."""
    m = conf["MEMORY_ROOT"]
    builds = collect(root, conf)
    artifacts = {}
    for b in builds:
        path = os.path.join(root, b["readme"])
        text = strip_records_sentence(read_text(path), b["readme"])
        text = apply_front_matter_ids(text, b["roster"], b["readme"])
        artifacts[b["readme"]] = apply_region(text, render_region(b), b["readme"])
    artifacts[f"{m}/LIVE.md"] = render_live(builds, m)
    artifacts.update(render_shards(builds, m))
    # Orphans: a tracked file under ledger/ that this render does not produce. The DELETABLE set is
    # bounded to the month-shard NAME; anything else is reported and left alone.
    tracked = [p for p in run("git", "ls-files", "--", f"{m}/ledger/", cwd=root).split("\n") if p]
    orphans, unmanaged = [], []
    for p in tracked:
        if p in artifacts:
            continue
        (orphans if SHARD_RE.match(os.path.basename(p)) and p.count("/") == 2 else unmanaged).append(p)
    return artifacts, sorted(orphans), sorted(unmanaged)


# -------------------------------------------------------------------------------------------- modes
def do_check(root: str, conf: dict) -> int:
    artifacts, orphans, unmanaged = plan(root, conf)
    bad = []
    for rel, want in sorted(artifacts.items()):
        path = os.path.join(root, rel)
        if not os.path.isfile(path):
            bad.append(f"{rel} (missing — never rendered)")
        elif read_text(path) != want:
            bad.append(f"{rel} (stale — differs from a fresh render)")
    for p in orphans:
        bad.append(f"{p} (orphaned ledger shard — no build opened in that month; --write deletes it)")
    for p in unmanaged:
        bad.append(f"{p} (unmanaged file under ledger/ — not a month shard; --write LEAVES IT ALONE)")
    if bad:
        print(f"build-index DRIFT — run: python {kit_rel()}/gen_build_index.py --write")
        for line in bad:
            print("    " + line)
        return 1
    print(f"build-index: clean ({len(artifacts)} artifact(s))")
    return 0


def do_write(root: str, conf: dict) -> int:
    artifacts, orphans, unmanaged = plan(root, conf)
    for rel, text in sorted(artifacts.items()):
        write_text(os.path.join(root, rel), text)
    for p in orphans:
        os.remove(os.path.join(root, p))
        print(f"build-index: removed orphaned shard {p}")
    for p in unmanaged:
        print(f"build-index: WARNING unmanaged file under ledger/ left in place: {p}")
    print(f"build-index: wrote {len(artifacts)} artifact(s)")
    return 0


# ----------------------------------------------------------------------------------------- selftest
def _fixture(tmp: str, *, marker=True, readme=True, status_key=None, spec_status="INPROGRESS"):
    run("git", "init", "-q", ".", cwd=tmp)
    run("git", "config", "user.email", "t@t.test", cwd=tmp)
    run("git", "config", "user.name", "t", cwd=tmp)
    write_text(os.path.join(tmp, ".memory-tree.conf"),
               'MEMORY_ROOT=memory\nDISCIPLINES="arch"\nFAMILIES="arch:ARCH"\n')
    d = os.path.join(tmp, "memory", "builds", "tOne", "spec")
    os.makedirs(d, exist_ok=True)
    if spec_status:
        write_text(os.path.join(d, "2026-08-01-spec-tOne-1.md"),
                   "# ARCH-tOne-1 — a unit\n\n**Status:** " + spec_status +
                   " · rev-1 · 2026-08-01 · node a · Tier-2 · base 0123abcd\n")
    else:
        write_text(os.path.join(d, "legacy-note.md"), "# no header here\n")
    if readme:
        fm = ["---", "slug: tOne", "node: a", "opened: 2026-08-01", "streams: arch",
              "roster: ARCH", "ids: ARCH-tOne-1"]
        if status_key:
            fm.append(f"status: {status_key}")
        fm.append("---")
        body = ["", "# tOne", ""]
        if marker:
            body += [MARK_OPEN, MARK_CLOSE]
        else:
            body += [MARK_OPEN]
        write_text(os.path.join(tmp, "memory", "builds", "tOne", "README.md"), "\n".join(fm + body) + "\n")
    run("git", "add", "-A", cwd=tmp)
    run("git", "commit", "-q", "-m", "f", "--no-verify", cwd=tmp)
    return load_conf(tmp)


def do_selftest() -> int:
    fails = []

    def arm(label, want, fn):
        try:
            got = fn()
        except Problem as exc:
            got = str(exc)
        except Exception as exc:  # noqa: BLE001 — a traceback here IS the finding
            got = f"UNEXPECTED {type(exc).__name__}: {exc}"
        if want in str(got):
            print(f"arm ok    {label}")
        else:
            fails.append(label)
            print(f"arm FAIL  {label} — expected to see: {want}\n      got: {got}")

    with tempfile.TemporaryDirectory() as base:
        # AC5 — a build leaves LIVE.md when its units go terminal, with nothing edited by hand.
        t = os.path.join(base, "live"); os.makedirs(t)
        conf = _fixture(t, spec_status="INPROGRESS")
        arm("live build appears in LIVE.md", "| [tOne](builds/tOne/README.md) | INPROGRESS",
            lambda: plan(t, conf)[0]["memory/LIVE.md"])
        t2 = os.path.join(base, "closed"); os.makedirs(t2)
        conf2 = _fixture(t2, spec_status="CLOSED")
        arm("terminal build leaves LIVE.md", "*No live build.*",
            lambda: plan(t2, conf2)[0]["memory/LIVE.md"])
        arm("terminal build still appears in its month shard", "| [tOne](../builds/tOne/README.md) | CLOSED",
            lambda: plan(t2, conf2)[0]["memory/ledger/2026-08.md"])

        # AC2 — an unpaired marker is a NAMED error, not a silent departure.
        t3 = os.path.join(base, "nomark"); os.makedirs(t3)
        conf3 = _fixture(t3, marker=False)
        arm("unpaired marker is named", "expected exactly one marker pair, found 1 open and 0 close",
            lambda: plan(t3, conf3))

        # The derived roster. Each arm names one branch of `rosters()`. (The owning spec is
        # deliberately NOT cited by id: a drift signal counts a non-terminal spec id appearing in
        # product source, and it sits at its pin.)
        def _roster_tree(name, extra=None, ids_line=None):
            """A fixture whose spec defines ARCH-tOne-1, plus whatever `extra` writes."""
            d = os.path.join(base, name); os.makedirs(d)
            c = _fixture(d, spec_status="INPROGRESS")
            if ids_line is not None:
                p = os.path.join(d, "memory", "builds", "tOne", "README.md")
                write_text(p, read_text(p).replace("ids: ARCH-tOne-1", ids_line))
            for rel, text in (extra or {}).items():
                full = os.path.join(d, rel.replace("/", os.sep))
                os.makedirs(os.path.dirname(full), exist_ok=True)
                write_text(full, text)
            run("git", "add", "-A", cwd=d)
            run("git", "commit", "-q", "-m", "r", "--no-verify", cwd=d)
            return d, c

        d1, c1 = _roster_tree("rosterbase", {"memory/DECISIONS.md": "- ARCH-tOne-4 · a decision\n"})
        arm("the roster is DERIVED, not read from front matter", "ids ARCH-tOne-1 ARCH-tOne-4",
            lambda: plan(d1, c1)[0]["memory/builds/tOne/README.md"])
        arm("the roster sorts by NUMERIC sequence, not lexically",
            "ARCH-tOne-2 ARCH-tOne-10",
            lambda: plan(*_roster_tree("rostersort",
                                       {"memory/DECISIONS.md": "- ARCH-tOne-10 · ten\n- ARCH-tOne-2 · two\n"}))[0]
            ["memory/builds/tOne/README.md"])
        # SELF-REFERENCE: the field must never be an input to itself, or a wrong value survives every
        # regeneration and every gate agrees, because a fresh render reproduces it exactly.
        d3, c3 = _roster_tree("rosterself", {"memory/DECISIONS.md": "- ARCH-tOne-4 · a decision\n"},
                              ids_line="ids: ARCH-tOne-1 ARCH-tOne-99")
        arm("an id present ONLY in the build's own front matter is dropped",
            "ids: ARCH-tOne-1 ARCH-tOne-4\n",
            lambda: plan(d3, c3)[0]["memory/builds/tOne/README.md"])
        # A revision-suffixed anchor amends a decision; it is not an id of its own. Admitting them
        # multiplied one real build's roster from 8 to 38.
        d4, c4 = _roster_tree("rosterrev", {"memory/DECISIONS.md": "- ARCH-tOne-4b · an amendment\n"})
        arm("a revision-suffixed anchor never joins a roster", "ids ARCH-tOne-1<",
            lambda: plan(d4, c4)[0]["memory/builds/tOne/README.md"].replace("\n", "<"))
        # The generated artifacts are rendered FROM the roster, so reading them is self-reference one
        # hop out. LIVE.md carries a COUNT for the same reason the region carries the list: only one
        # of the two files is inside check 7's entry budget.
        d5, c5 = _roster_tree("rosterexcl", {"memory/LIVE.md": "ARCH-tOne-77\n",
                                             "memory/ledger/2026-08.md": "ARCH-tOne-88\n"})
        arm("an id present only in a GENERATED artifact never joins a roster", "ids ARCH-tOne-1<",
            lambda: plan(d5, c5)[0]["memory/builds/tOne/README.md"].replace("\n", "<"))
        arm("the capped artifacts carry a COUNT, never the id list", "| arch | 2 |",
            lambda: plan(d1, c1)[0]["memory/LIVE.md"])

        # ---- the folder-claim sentence. These are FIXTURE arms on purpose: once the corpus is
        # ---- migrated the sentence is gone from it, so a control run against the live tree has
        # ---- nothing left to catch and passes whatever the remover does.
        def _rec(tmp, body):
            c = _fixture(tmp, spec_status="INPROGRESS")
            p = os.path.join(tmp, "memory", "builds", "tOne", "README.md")
            t = read_text(p)
            write_text(p, t.replace("# tOne\n", "# tOne\n\n" + body + "\n"))
            run("git", "add", "-A", cwd=tmp)
            run("git", "commit", "-q", "-m", "r", "--no-verify", cwd=tmp)
            return c

        ta = os.path.join(base, "recsurv"); os.makedirs(ta)
        ca = _rec(ta, "Records live under `spec/`. The table below is\nGENERATED from the header.")
        arm("the text following the sentence SURVIVES the removal", "The table below is",
            lambda: plan(ta, ca)[0]["memory/builds/tOne/README.md"])
        arm("the authored sentence leaves the body", "1",
            lambda: str(plan(ta, ca)[0]["memory/builds/tOne/README.md"].count("Records live under")))
        tb = os.path.join(base, "recwhole"); os.makedirs(tb)
        cb = _rec(tb, "Records live under `spec/`.")
        arm("a line that was ONLY the sentence is removed entirely", "1",
            lambda: str(plan(tb, cb)[0]["memory/builds/tOne/README.md"].count("Records live under")))
        tc = os.path.join(base, "rectwice"); os.makedirs(tc)
        cc = _rec(tc, "Records live under `spec/`. one\n\nRecords live under `build/`. two")
        arm("the sentence appearing twice outside the region is a REFUSAL",
            "is not identifying one sentence", lambda: plan(tc, cc))
        arm("the derived sentence names only the folders that exist", "Records live under `spec/`.",
            lambda: plan(ta, ca)[0]["memory/builds/tOne/README.md"])

        # AC4 — an absent README is a named error on BOTH modes, never a traceback.
        t4 = os.path.join(base, "noreadme"); os.makedirs(t4)
        conf4 = _fixture(t4, readme=False)
        arm("absent README is named, not a traceback", "no tracked README.md",
            lambda: plan(t4, conf4))

        # AC8 — the status: fallback, both arms.
        t5 = os.path.join(base, "noheader"); os.makedirs(t5)
        conf5 = _fixture(t5, spec_status=None)
        arm("no parseable header and no status: is named", "declare it explicitly with a 'status:'",
            lambda: plan(t5, conf5))
        t6 = os.path.join(base, "declared"); os.makedirs(t6)
        conf6 = _fixture(t6, spec_status=None, status_key="SPECCED")
        arm("declared status is used when nothing is derivable", "| SPECCED |",
            lambda: plan(t6, conf6)[0]["memory/LIVE.md"])
        t7 = os.path.join(base, "conflict"); os.makedirs(t7)
        conf7 = _fixture(t7, spec_status="OPEN", status_key="CLOSED")
        arm("declared status alongside a derivable one is a conflict", "two answers to one",
            lambda: plan(t7, conf7))

        # AC3 — orphan handling, and its BOUND.
        t8 = os.path.join(base, "orphan"); os.makedirs(t8)
        conf8 = _fixture(t8, spec_status="OPEN")
        write_text(os.path.join(t8, "memory", "ledger", "1999-01.md"), "stale\n")
        write_text(os.path.join(t8, "memory", "ledger", "notes.md"), "authored\n")
        run("git", "add", "-A", cwd=t8)
        run("git", "commit", "-q", "-m", "orphans", "--no-verify", cwd=t8)
        arm("an orphaned month shard is reported", "memory/ledger/1999-01.md",
            lambda: str(plan(t8, conf8)[1]))
        arm("a non-shard file under ledger/ is NOT deletable", "memory/ledger/notes.md",
            lambda: str(plan(t8, conf8)[2]))
        do_write(t8, conf8)
        arm("--write removed the orphan", "False",
            lambda: str(os.path.exists(os.path.join(t8, "memory", "ledger", "1999-01.md"))))
        arm("--write kept the unmanaged file", "True",
            lambda: str(os.path.exists(os.path.join(t8, "memory", "ledger", "notes.md"))))

        # front matter: line 1 only, keys at column 0.
        t9 = os.path.join(base, "fm"); os.makedirs(t9)
        conf9 = _fixture(t9, spec_status="OPEN")
        rd = os.path.join(t9, "memory", "builds", "tOne", "README.md")
        write_text(rd, "# a heading first\n\n" + read_text(rd))
        arm("front matter must open at line 1", "line 1 must be '---'", lambda: plan(t9, conf9))
        t10 = os.path.join(base, "indent"); os.makedirs(t10)
        conf10 = _fixture(t10, spec_status="OPEN")
        rd10 = os.path.join(t10, "memory", "builds", "tOne", "README.md")
        write_text(rd10, read_text(rd10).replace("node: a", "  node: a"))
        arm("an indented front-matter key is named", "keys live at COLUMN 0", lambda: plan(t10, conf10))

        # --write then --check is a fixed point. Without this a renderer that emits CRLF, or a
        # comparison that normalises differently from the writer, is green on the run that wrote it
        # and red forever after.
        t11 = os.path.join(base, "roundtrip"); os.makedirs(t11)
        conf11 = _fixture(t11, spec_status="OPEN")
        do_write(t11, conf11)
        arm("write then check is a fixed point", "0", lambda: str(do_check(t11, conf11)))

    if fails:
        print(f"FAIL — {len(fails)} arm(s) failed")
        return 1
    print("PASS — gen_build_index: all arms held")
    return 0


def main(argv: list) -> int:
    mode = argv[1] if len(argv) > 1 else "--check"
    if mode == "--selftest":
        return do_selftest()
    if mode not in ("--check", "--write"):
        print("usage: gen_build_index.py [--check|--write|--selftest]")
        return 2
    try:
        root = run("git", "rev-parse", "--show-toplevel").strip()
    except Exception:  # noqa: BLE001
        print("build-index: not a git repo")
        return 2
    conf = load_conf(root)
    try:
        return do_check(root, conf) if mode == "--check" else do_write(root, conf)
    except Problem as exc:
        print(f"build-index: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
