#!/usr/bin/env python3
"""gen_build_index.py — the generated build index for a flat memory tree (memory-tree kit 1.5).

    python tools/memory-tree/gen_build_index.py --check      # drift gate (writes nothing)
    python tools/memory-tree/gen_build_index.py --write      # (re)render every artifact
    python tools/memory-tree/gen_build_index.py --selftest    # fixtures, in a temp dir

It replaces the retired directory-listing generator. A listing carried paths, which git already
prints better; this carries STATUS, which git does not — and a build's status is a PURE FUNCTION of
its units' statuses, so nothing here is authored and nothing rots.

THREE SOURCES, NOTHING ELSE
  * each build's README front matter (slug node opened streams roster [status])
  * every `**Status:**` header under that build's spec/, at any depth
  * for the ROSTER only, every tracked file under the memory root EXCEPT this field's own outputs —
    the build's own README and the generated index and shards. `ids` is therefore an OUTPUT, not a
    source: `--write` overwrites whatever was authored there.
No git history and no mtimes. A source the renderer does not read cannot make the render drift; a
source the renderer WRITES must not also be read, or a wrong value defends itself forever.

ONE SOURCE OF TRUTH PER BUILD
  * any spec carries a parseable header -> the status is DERIVED, and an authored `status:` is an
    ERROR (two answers to one question is the drift this file exists to remove);
  * no spec carries one -> `status:` is REQUIRED, and its absence is a named error.
Three builds in the originating corpus are grandfathered recordings with no status header at all;
every plausible default for them was wrong, so the fallback is explicit and gated instead.

THE THREE BLIND SPOTS THIS CLOSES (each armed in --selftest)
  1. a README with no marker PAIR used to leave the universe silently -> named error;
  2. an orphaned generated file was permanent and invisible -> reported, and removed by --write,
     BOUNDED to a `ledger/<YYYY-MM>.md` name; anything else in ledger/ is reported and left alone,
     because a generator that deletes inside the memory tree on its own authority is a data-loss path;
  3. an absent README killed both modes with a traceback -> named error, never a stack.
"""
from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys
import tempfile

CR = chr(13)   # one carriage return; see _is() and _one_cr()
RECORD_KINDS = ("spec", "build", "reviews", "prompts")
MARK_OPEN = "<!-- gen:build-index -->"
MARK_CLOSE = "<!-- /gen:build-index -->"

# The AUTHORED plan region. This generator NEVER writes between these two markers: the unattended
# kit's check_authorization byte-compares that slice across a run's pinned BASE, so a renderer that
# touched it would silently invalidate every run authorized against the file. It is listed here so
# the slot walk can FIND it, not so anything can render into it.
PLAN_OPEN = "<!-- roster:units -->"
PLAN_CLOSE = "<!-- /roster:units -->"

# Every generated region, in CANONICAL SLOT ORDER. `--write` creates a missing pair at its position
# here; `--check` never demands one (TOOL-aRuledFrontispiece-1 S1c). The order is a property of this
# list rather than of whoever edited a README last.
#
# The renderer is looked up by name at call time rather than stored, so this stays a plain data
# declaration and a region cannot be half-registered.
GEN_REGIONS = (
    ("build-index", MARK_OPEN, MARK_CLOSE),
    ("build-order", "<!-- gen:build-order -->", "<!-- /gen:build-order -->"),
    ("build-edges", "<!-- gen:build-edges -->", "<!-- /gen:build-edges -->"),
    ("build-docs", "<!-- gen:build-docs -->", "<!-- /gen:build-docs -->"),
)
# The stamped header names THIS install's prefix, derived from the module's own location rather
# than spelled. It is written INTO the adopter's generated artifacts and committed there, so a
# hardcoded prefix does not merely mislead — it lands a dead path in their tree, and the byte-compare
# that guards these files happily agrees with it. `kit_rel()` falls back to the bare kit name when the
# module sits outside the resolved root (a test fixture, an odd checkout); the header is a pointer,
# never a gate input.
def kit_rel() -> str:
    here = pathlib.Path(__file__).resolve().parent
    for anc in [here] + list(here.parents):
        if (anc / ".git").exists():
            try:
                return here.relative_to(anc).as_posix()
            except ValueError:
                break
    return here.name


GEN_HEADER = (
    f"<!-- generated by {kit_rel()}/gen_build_index.py --write — do not hand-edit -->"
)

STATUS_TOKENS = ("OPEN", "SPECCED", "INPROGRESS", "BLOCKED", "DEFERRED", "CLOSED", "WONTDO")
TERMINAL = ("CLOSED", "WONTDO")
# Precedence for the derived status, most-live first. A build is as live as its liveliest unit.
PRECEDENCE = ("INPROGRESS", "BLOCKED", "OPEN", "SPECCED", "DEFERRED")

HDR_RE = re.compile(
    r"^\*\*Status:\*\* (?P<token>" + "|".join(STATUS_TOKENS) + r")"
    r" · rev-(?P<rev>\d+) · (?P<date>\d{4}-\d{2}-\d{2}) · node (?P<node>[a-z])"
    r" · Tier-(?P<tier>[12]) · base (?P<base>[0-9a-f]{8,})"
)
H1_RE = re.compile(r"^#\s+(?P<id>[A-Za-z0-9][A-Za-z0-9-]*)\s+—\s+(?P<title>.+?)\s*$")
# The build-order verb, appended after `base` in a spec's status header. Units sharing a value are
# the parallel group; the owner resolved against a second `group` verb, which would have needed its
# own contradiction refusals to render an identical region.
ORDER_RE = re.compile(r"·\s*order\s+(\d+)(?![0-9])")
SHARD_RE = re.compile(r"^\d{4}-\d{2}\.md$")
REQUIRED_KEYS = ("slug", "node", "opened", "streams", "roster", "ids")


class Problem(Exception):
    """A named, user-facing failure. Never a traceback: blind spot 3."""


# --------------------------------------------------------------------------------------- plumbing
def run(*argv: str, cwd: str | None = None) -> str:
    return subprocess.run(argv, cwd=cwd, capture_output=True, text=True, check=True).stdout


def read_text(path: str) -> str:
    # Bytes in, decode, normalise CR. Windows checkouts hand back CRLF and every comparison below
    # would then differ on every line — the exact green-by-accident shape a byte gate must not have.
    with open(path, "rb") as fh:
        return fh.read().decode("utf-8").replace("\r\n", "\n")


def write_text(path: str, text: str) -> None:
    # BYTES, never write_text(): on Windows the text mode would re-expand \n to \r\n and the very
    # next --check would report the file this call just wrote as stale.
    os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(path) else None
    with open(path, "wb") as fh:
        fh.write(text.encode("utf-8"))


def load_conf(root: str) -> dict:
    conf = {"MEMORY_ROOT": "memory", "DISCIPLINES": "", "FAMILIES": ""}
    path = os.path.join(root, ".memory-tree.conf")
    if os.path.isfile(path):
        for line in read_text(path).split("\n"):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            conf[k.strip()] = v.strip().strip('"').strip("'")
    return conf


def unfenced_lines(text: str):
    """Yield (lineno, line) for every line OUTSIDE a fenced block, then the open fence's line.

    The final yield is `(opened_at, None)` when the document ends inside a fence, and nothing when it
    does not. A caller that only wants the text ignores it; a caller that must REFUSE a document it
    could not fully read needs it, and no reader in either kit had it — the shell `_unfenced` and this
    module's own generator both end silently with the fence still open, dropping every later line at
    exit 0. That is invisible by construction: a fence opened near the top of a row document hides
    every duplicate below it, and hiding duplicates is what the check that reads this exists to stop.
    """
    fence = ""
    opened_at = 0
    for n, line in enumerate(text.split("\n"), 1):
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            mark = "```" if stripped.startswith("```") else "~~~"
            if not fence:
                fence, opened_at = mark, n
                continue
            # Only the marker that OPENED the fence closes it: a ``` line inside a ~~~ block is
            # content, not a toggle.
            if mark == fence:
                fence = ""
                continue
        if not fence:
            yield n, line
    if fence:
        yield opened_at, None


def unfenced(text: str):
    """The text-only view, kept as the one fence machine's façade rather than a second copy."""
    for _n, line in unfenced_lines(text):
        if line is not None:
            yield line


# ----------------------------------------------------------------------------------------- parsing
def parse_front_matter(path: str, slug: str) -> dict:
    """Front matter opens at LINE 1 and nowhere else.

    `---` is also a markdown horizontal rule, and one already separates the two merged halves of a
    real build README in the originating corpus. A parser that scanned for the first two `---`
    anywhere would swallow that whole half as front matter.
    """
    lines = read_text(path).split("\n")
    if not lines or lines[0].strip() != "---":
        raise Problem(f"{path}: no front matter — line 1 must be '---' (build '{slug}')")
    fm: dict = {}
    end = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
        if not line.strip():
            continue
        if line[:1].isspace():
            raise Problem(
                f"{path}:{i + 1}: front-matter key is indented — keys live at COLUMN 0, and an "
                f"indented key is silently dropped by every simple parser"
            )
        if ":" not in line:
            raise Problem(f"{path}:{i + 1}: front-matter line is not 'key: value'")
        k, _, v = line.partition(":")
        fm[k.strip()] = v.strip()
    if end is None:
        raise Problem(f"{path}: front matter opened at line 1 but never closed with '---'")
    missing = [k for k in REQUIRED_KEYS if k not in fm]
    if missing:
        raise Problem(f"{path}: front matter missing required key(s): {', '.join(missing)}")
    if fm["slug"] != slug:
        raise Problem(f"{path}: front matter slug '{fm['slug']}' != folder name '{slug}'")
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", fm["opened"]):
        raise Problem(f"{path}: opened '{fm['opened']}' is not a YYYY-MM-DD date")
    if "status" in fm and fm["status"] not in STATUS_TOKENS:
        raise Problem(f"{path}: status '{fm['status']}' is not one of {' '.join(STATUS_TOKENS)}")
    return fm


def parse_spec(path: str) -> dict | None:
    """Return the unit record, or None when the file carries no parseable status header.

    A grandfathered recording legitimately has none; check 12 already rejects a post-cutoff spec
    that is missing one, so this file never has to defend against a malformed header.
    """
    body = list(unfenced(read_text(path)))
    hdr = None
    for line in body[:5]:
        m = HDR_RE.match(line)
        if m:
            hdr = m
            break
    if hdr is None:
        return None
    unit_id, title = os.path.basename(path)[:-3], ""
    for line in body[:5]:
        m = H1_RE.match(line)
        if m:
            unit_id, title = m.group("id"), m.group("title")
            break
    return {
        "path": path,
        "id": unit_id,
        "title": title,
        "status": hdr.group("token"),
        "rev": hdr.group("rev"),
        "date": hdr.group("date"),
        # PERMITTED, never required (fork 5). HDR_RE has no end anchor, so a header carrying this
        # verb parses identically with or without it and no landed spec goes retroactively red.
        "order": (lambda mo: int(mo.group(1)) if mo else None)(ORDER_RE.search(hdr.string)),
    }


# ------------------------------------------------------------------------------ record -> spec bindings
# Every record under a build's non-spec folders names the spec(s) it is
# evidence about, in its own head. This parser READS that and CLASSIFIES; it never raises, because
# `collect()` is reached by both --check and --write through one call site, so a raising parser would
# let one unannotated record refuse to render every artifact.
BIND_HEAD_LINES = 12
RECORD_KIND_TOKENS = ("spec-audit", "diff-review", "journal", "research")
# Optional leading whitespace and an optional comment marker: the corpus holds a non-markdown record
# (a shell script), where the line can only be a comment. An extension-scoped rule would structurally
# exclude the one file most easily forgotten.
BIND_RE = re.compile(
    r"^[ \t]*(?:#+|//|;)?[ \t]*\*\*(?P<key>Serves|Commissions):\*\*[ \t]+(?P<rest>.*\S)[ \t]*$"
)
UNBOUND_RE = re.compile(r"^none\b[\s—–:-]*(?P<reason>\S.*)$")


def _id_alternation(conf: dict) -> str:
    fams = [p.split(":", 1)[1] for p in conf.get("FAMILIES", "").split() if ":" in p]
    return "|".join(sorted(fams)) or "(?!)"


def spec_ids(root: str, tracked: list, conf: dict) -> set:
    """The resolution set: ids DEFINED by a spec H1, one per file, at any depth under a build's spec/.

    Deliberately NOT the build README `ids:` roster. That roster is a reservation RANGE generated from
    citations anywhere, and it admits backlog and decision rows as if they were units — measured on
    this corpus, two thirds of its ids had no spec at all. Resolving a record against it would let a
    binding name something no spec ever defined.
    """
    m = conf["MEMORY_ROOT"]
    pat = re.compile(r"^#\s+[`*]*(?P<id>(?:" + _id_alternation(conf) + r")-[A-Za-z0-9]+-\d+)\b")
    sel = re.compile(r"^" + re.escape(m) + r"/builds/[^/]+/spec/")
    out = set()
    for rel in tracked:
        if not sel.match(rel):
            continue
        try:
            for line in unfenced(read_text(os.path.join(root, rel))):
                mm = pat.match(line)
                if mm:
                    out.add(mm.group("id"))
                    break
        except OSError:
            continue
    return out


def record_paths(tracked: list, m: str) -> list:
    """Every tracked record: any depth, ANY extension, under a build's non-spec kind folders."""
    kinds = "|".join(k for k in RECORD_KINDS if k != "spec")
    sel = re.compile(r"^" + re.escape(m) + r"/builds/[^/]+/(?:" + kinds + r")/")
    return [p for p in tracked if sel.match(p)]


def _expand_ids(rest: str, alt: str) -> tuple:
    """Return (ids, bad_tokens). A contiguous run may be written N..M and EXPANDS here, at authoring
    time, to a fixed set — unlike a wildcard it cannot rot when the build later gains a unit."""
    ids, bad = [], []
    one = re.compile(r"^(?P<fam>" + alt + r")-(?P<slug>[A-Za-z0-9]+)-(?P<seq>\d+)(?:@rev-\d+)?$")
    rng = re.compile(r"^(?P<fam>" + alt + r")-(?P<slug>[A-Za-z0-9]+)-(?P<lo>\d+)\.\.(?P<hi>\d+)$")
    for tok in rest.split():
        mo = one.match(tok)
        if mo:
            ids.append(f"{mo.group('fam')}-{mo.group('slug')}-{mo.group('seq')}")
            continue
        mr = rng.match(tok)
        if mr and int(mr.group("lo")) <= int(mr.group("hi")):
            for n in range(int(mr.group("lo")), int(mr.group("hi")) + 1):
                ids.append(f"{mr.group('fam')}-{mr.group('slug')}-{n}")
            continue
        bad.append(tok)
    return ids, bad


def read_bindings(root: str, tracked: list, conf: dict) -> dict:
    """path -> {state, kind, ids, commissions, reason, bad}. Never raises.

    state is one of: bound · unbound · malformed · absent.
    """
    m = conf["MEMORY_ROOT"]
    alt = _id_alternation(conf)
    out = {}
    for rel in record_paths(tracked, m):
        rec = {"state": "absent", "kind": None, "ids": [], "commissions": [], "reason": None,
               "bad": [], "why": "no Serves line in the first %d unfenced lines" % BIND_HEAD_LINES}
        try:
            text = read_text(os.path.join(root, rel))
        except OSError as exc:
            rec["why"] = f"unreadable: {exc}"
            out[rel] = rec
            continue
        for line in list(unfenced(text))[:BIND_HEAD_LINES]:
            mo = BIND_RE.match(line)
            if not mo:
                continue
            # A trailing HTML comment is a NOTE, not a token. The retrofit records the adjudication
            # rule that produced an inferred binding on the line itself, so a reviewer grades it in
            # the file rather than in a commit body no gate reads — and without this the note's
            # every word parsed as a malformed id.
            rest = mo.group("rest").split("<!--", 1)[0].strip()
            if not rest:
                continue
            if mo.group("key") == "Commissions":
                cids, bad = _expand_ids(rest, alt)
                rec["commissions"] = cids
                rec["bad"] += bad
                continue
            if rec["state"] != "absent":
                continue                      # first Serves line wins
            un = UNBOUND_RE.match(rest)
            if un:
                # The kind is OPTIONAL here and required below: an unbound record names no ids, so
                # there is no relation for a kind token to describe. The REASON is mandatory either
                # way — a bare `none` is malformed, because "no gate named" and "gate not yet
                # written" are indistinguishable from outside and only one of them is acceptable.
                rec["state"] = "unbound"
                rec["reason"] = un.group("reason")
                rec["why"] = ""
                continue
            toks = rest.split()
            if toks and toks[0] in RECORD_KIND_TOKENS:
                ids, bad = _expand_ids(" ".join(toks[1:]), alt)
                rec["kind"] = toks[0]
                rec["ids"] = ids
                rec["bad"] += bad
                if not ids:
                    rec["state"] = "malformed"
                    rec["why"] = "kind token with no resolvable id"
                else:
                    rec["state"] = "bound"
                    rec["why"] = ""
            else:
                rec["state"] = "malformed"
                got = toks[0] if toks else "(empty)"
                rec["why"] = (f"first token {got} is not one of "
                              + " ".join(RECORD_KIND_TOKENS) + ", and the line is not the none form")
        out[rel] = rec
    return out


def do_print_bindings(root: str, conf: dict) -> int:
    """READ-ONLY. Classifies and prints; writes nothing and always exits 0.

    It is the retrofit's own checklist AND the predicate the gate reads, so a seed list and a gate
    that disagree is structurally impossible here.
    """
    m = conf["MEMORY_ROOT"]
    tracked = [p for p in run("git", "ls-files", cwd=root).split("\n") if p]
    defined = spec_ids(root, tracked, conf)
    binds = read_bindings(root, tracked, conf)
    unbound = 0
    for rel in sorted(binds):
        rec = binds[rel]
        if rec["state"] in ("absent", "malformed"):
            print(f"A\t{rel}\t{rec['why']}")
            continue
        if rec["state"] == "unbound":
            unbound += 1
        # One S row per BOUND record, carrying the resolved SET. A conformant record is not a
        # finding, so the A/B/N rows say nothing about it — and check 21's filename-vs-header
        # branch needs exactly this set to test membership against. Without it that branch would
        # have to parse every record a second time, which is the two-answers class in the one
        # place this build exists to remove it.
        if rec["state"] == "bound":
            print(f"S\t{rel}\t{rec['kind']}\t{' '.join(rec['ids'])}")
        for tok in rec["bad"]:
            print(f"B\t{rel}\t{tok} is not a family-qualified id or range")
        for i in rec["ids"] + rec["commissions"]:
            if i not in defined:
                print(f"B\t{rel}\t{i} is named but no spec H1 in this tree defines it")
    print(f"N\t{unbound}")
    return 0


def derive_status(units: list, fm: dict, readme: str) -> str:
    parsed = [u for u in units if u]
    if not parsed:
        if "status" not in fm:
            raise Problem(
                f"{readme}: no spec under this build carries a parseable **Status:** header, so the "
                f"build status cannot be derived — declare it explicitly with a 'status:' front-matter key"
            )
        return fm["status"]
    if "status" in fm:
        raise Problem(
            f"{readme}: front matter declares 'status: {fm['status']}' but {len(parsed)} spec(s) "
            f"carry a status header — the build status is DERIVED from them, and two answers to one "
            f"question is exactly the drift this index removes. Delete the 'status:' key."
        )
    seen = {u["status"] for u in parsed}
    for token in PRECEDENCE:
        if token in seen:
            return token
    return "WONTDO" if seen == {"WONTDO"} else "CLOSED"


# ----------------------------------------------------------------------------------- roster scanning
def _roster_sort_key(i: str):
    """Family, then NUMERIC sequence. Lexical order puts `-10` before `-2`, which reads as data loss
    to anyone scanning the rendered list for the newest id."""
    return (i.split("-", 1)[0], int(i.rsplit("-", 1)[1]))


def rosters(root: str, tracked: list, m: str, families: set) -> dict:
    """slug -> sorted ids belonging to that build, from the id's own slug component.

    An id spells its build: family-slug-sequence. So a build's roster needs no side table and no
    anchor grammar — only the declared family alternation, which this module already loads. The
    sequence must be all DIGITS: revision-suffixed anchors (`-6q`) are amendments to a decision, not
    ids of their own, and admitting them multiplied one build's roster from 8 to 38.

    THE READ SET EXCLUDES THIS FIELD'S OWN OUTPUTS. A build's README is skipped for its OWN slug, and
    the generated index and shards are skipped entirely, because all three are rendered FROM the
    value being derived. A derivation that reads its own output cannot correct a wrong value — it
    republishes it forever, and every gate agrees, because a fresh render reproduces it exactly. That
    is the defect this change exists to remove, so it must not be reintroduced by the fix.
    """
    fam = "|".join(sorted(re.escape(f) for f in families))
    if not fam:
        raise Problem("build-index: FAMILIES is empty, so no id can be recognised and every roster "
                      "would render empty — which is also what a clean corpus looks like")
    id_re = re.compile(r"\b(?:" + fam + r")-([A-Za-z0-9]+)-\d+\b")
    out: dict = {}
    for p in tracked:
        if p == f"{m}/LIVE.md" or p.startswith(f"{m}/ledger/"):
            continue
        try:
            text = read_text(os.path.join(root, p))
        except Problem:
            continue
        for mm in id_re.finditer(text):
            slug = mm.group(1)
            if p == f"{m}/builds/{slug}/README.md":
                continue
            out.setdefault(slug, set()).add(mm.group(0))
    return {s: sorted(v, key=_roster_sort_key) for s, v in out.items()}


# --------------------------------------------------------------------------------------- collecting
def collect(root: str, conf: dict) -> list:
    m = conf["MEMORY_ROOT"]
    tracked = [p for p in run("git", "ls-files", "--", m + "/", cwd=root).split("\n") if p]
    slugs = sorted({p.split("/")[2] for p in tracked if p.startswith(m + "/builds/") and p.count("/") >= 3})
    disciplines = set(conf["DISCIPLINES"].split())
    families = {pair.split(":")[1] for pair in conf["FAMILIES"].split() if ":" in pair}
    # Two granularities, as the hygiene engine's own guard does it. The PRECONDITION asks whether the
    # scan recognised anything at all; the per-build POPULATION asks whether this build did. Without
    # the first, a families list bound to the wrong tree renders every roster empty — and an empty
    # classification is exactly what a clean corpus yields, so the failure would look like success.
    roster_by_slug = rosters(root, tracked, m, families)
    # NO EMPTINESS PRECONDITION HERE, deliberately. The wrong-root class says an unrecognising
    # grammar yields the same empty result a clean corpus does, so a guard is wanted — but every
    # signal available HERE is one this function derives from the same conf, which makes the
    # assertion a tautology (the repo's assertion-between-two-derived-values class). Build count
    # fails on a sparse tree; spec-file existence fails too, because a legacy recording legitimately
    # carries no id. The guard that actually holds is INDEPENDENT and already runs below: every
    # build's authored `roster:` value must be a declared family, so a FAMILIES list bound to the
    # wrong tree reds there, by name, before any roster is rendered.
    builds = []
    for slug in slugs:
        readme = f"{m}/builds/{slug}/README.md"
        if readme not in tracked:
            raise Problem(
                f"{m}/builds/{slug}/: no tracked README.md — a build with no front matter cannot be "
                f"indexed, and an unindexed build is a silent departure from the universe"
            )
        fm = parse_front_matter(os.path.join(root, readme), slug)
        for value in fm["streams"].split("+"):
            if disciplines and value.strip() not in disciplines:
                raise Problem(f"{readme}: streams value '{value.strip()}' is outside the DISCIPLINES enum")
        for value in fm["roster"].split("+"):
            if families and value.strip() not in families:
                raise Problem(f"{readme}: roster value '{value.strip()}' is outside the FAMILIES set")
        specs = sorted(p for p in tracked if p.startswith(f"{m}/builds/{slug}/spec/") and p.endswith(".md"))
        units = [parse_spec(os.path.join(root, p)) for p in specs]
        # BOOTSTRAP, not failure. A build whose ids appear nowhere but its own README is young, not
        # broken, and there is nothing to correct the authored value against — so it stands. The
        # anti-self-reference property still holds where it can bite: the moment any independent
        # source names the id, the derivation takes over and a wrong authored value loses. Global
        # emptiness is the dangerous case, and the precondition above owns it.
        roster = roster_by_slug.get(slug) or [i for i in fm["ids"].split() if i]
        # Which record folders this build actually HAS. Authored as prose in 17 READMEs and wrong
        # in 15 of them: the sentence is written when a build opens, predicting the folders it will
        # grow, and nothing revisits it. Seven claim a build/ that was never created.
        kinds = [k for k in RECORD_KINDS
                 if any(t.startswith(f"{m}/builds/{slug}/{k}/") for t in tracked)]
        builds.append(
            {
                "slug": slug,
                "readme": readme,
                "fm": fm,
                "roster": roster,
                "kinds": kinds,
                # Every tracked record, for the document-inventory region. The filename grammar is
                # NOT parsed: five files under legacy-files.txt carry grandfathered names, and a
                # renderer that parsed names would have to waive them or render them degraded.
                "docs": sorted(t for t in tracked
                               if any(t.startswith(f"{m}/builds/{slug}/{k}/") for k in RECORD_KINDS)),
                "parents": [s.strip() for s in fm.get("parents", "").split() if s.strip()],
                "units": [u for u in units if u],
                "status": derive_status(units, fm, readme),
            }
        )
    return builds


# ---------------------------------------------------------------------------------------- rendering
def render_region(build: dict) -> str:
    fm = build["fm"]
    out = [
        MARK_OPEN,
        # `unit(s)` and `ids` answer DIFFERENT questions and are deliberately not reconciled: a unit
        # is a spec carrying a status header, a roster member is an id that exists in the record.
        # aUnmannedHelm is 7 and 10 because three of its ids never got a spec. Rendering them as one
        # number would re-create, inverted, the defect this derivation removes.
        f"**Build status:** {build['status']} · {len(build['units'])} unit(s) · node {fm['node']} · "
        f"opened {fm['opened']} · streams {fm['streams']}",
    ]
    # THE FULL ROSTER STAYS, WRAPPED. Replacing it with a count would reverse TOOL-aMouldedFolio-2 S4,
    # which deliberately renders the full roster HERE and only the count in LIVE.md and the ledger —
    # and render_region's own comment above says `unit(s)` and `ids` answer different questions.
    #
    # WRAPPED AT 300, one tier BELOW the 350 this class is capped at. `length()` in the entry-budget
    # awk counts bytes or characters depending on the awk build and the ambient locale, which that
    # check's own comment refuses to pin — and this line carries six two-byte middots. A render
    # sitting exactly at the cap would pass on one node and red on another.
    out += _wrap_ids(build["roster"])
    out.append("")
    if build["units"]:
        out += ["| Unit | Status | Rev | Last change |", "|---|---|---|---|"]
        for u in sorted(build["units"], key=lambda x: x["path"]):
            rel = u["path"].split(f"/builds/{build['slug']}/", 1)[1]
            label = f"{u['id']} — {u['title']}" if u["title"] else u["id"]
            out.append(f"| [{label}]({rel}) | {u['status']} | rev-{u['rev']} | {u['date']} |")
    else:
        out.append("*No spec under this build carries a status header; the status above is declared "
                   "in the front matter.*")
    if build["kinds"]:
        ks = [f"`{k}/`" for k in build["kinds"]]
        joined = ks[0] if len(ks) == 1 else ", ".join(ks[:-1]) + " and " + ks[-1]
        out += ["", f"Records live under {joined}."]
    # The records table and the two coverage joins. The sentence above is KEPT rather than replaced:
    # `strip_records_sentence` manages it and several arms detect a mis-segmented record selector by
    # noticing the sentence went missing, so replacing it would remove the thing they watch.
    recs = build.get("records") or []
    if recs:
        out += ["", "| Record | Kind | Serves |", "|---|---|---|"]
        for r in sorted(recs, key=lambda x: x["path"]):
            rel = r["path"].split(f"/builds/{build['slug']}/", 1)[1]
            label = rel.rsplit("/", 1)[-1]
            if r["state"] == "unbound":
                out.append(f"| [{label}]({rel}) | — | *none — {r['reason']}* |")
            else:
                out.append(f"| [{label}]({rel}) | {r['kind']} | {' '.join(r['ids'])} |")
        named = {i for r in recs for i in r.get("ids", [])}
        audited = {i for r in recs if r.get("kind") == "spec-audit" for i in r.get("ids", [])}
        own = [u["id"] for u in build["units"]]
        gap = [i for i in own if i not in named]
        agap = [i for i in own if i not in audited]
        if gap:
            out += ["", f"Ids no record names: {' '.join(gap)}."]
        if agap:
            # NOT "unreviewed". The reviewed rev is optional, so this reports ids no spec-audit
            # record names EVER — a spec audited at rev-1 and since bumped does not appear here.
            # An "unreviewed" label would be a coverage claim the data cannot support.
            out += ["", f"Ids no `spec-audit` record has ever named: {' '.join(agap)}."]
    out.append(MARK_CLOSE)
    return "\n".join(out)


IDS_WRAP = 300


def _wrap_ids(roster: list) -> list:
    """`ids` as one or more lines, none wider than IDS_WRAP. Empty roster renders no line at all."""
    if not roster:
        return []
    lines, cur = [], "ids"
    for i in roster:
        if len(cur) + 1 + len(i) > IDS_WRAP and cur != "ids":
            lines.append(cur)
            cur = "ids"
        cur += " " + i
    lines.append(cur)
    return lines


def render_order(build: dict) -> str:
    """The BUILD ORDER region. Units sharing an `order` value are the parallel group."""
    mo, mc = GEN_REGIONS[1][1], GEN_REGIONS[1][2]
    out = [mo, ""]
    steps = {}
    for u in build["units"]:
        if u.get("order") is not None:
            steps.setdefault(u["order"], []).append(u)
    if not steps:
        out.append("*No spec under this build declares an `order` verb; the build order is whatever "
                   "its authored plan states.*")
    else:
        out += ["| Step | Units | Parallel |", "|---|---|---|"]
        for n in sorted(steps):
            us = sorted(steps[n], key=lambda x: x["id"])
            ids = ", ".join(f"`{u['id']}`" for u in us)
            out.append(f"| {n} | {ids} | {'yes' if len(us) > 1 else 'no'} |")
        # RESIDUAL, stated rather than silently dropped: a unit with no verb is not ordered, and a
        # region that omitted it would read as a complete order while hiding a unit.
        rest = sorted((u["id"] for u in build["units"] if u.get("order") is None))
        if rest:
            out += ["", "Unordered: " + ", ".join(f"`{i}`" for i in rest) + "."]
    out.append(mc)
    return "\n".join(out)


def render_edges(build: dict) -> str:
    """The DEPENDENCY EDGE region. `parents:` is AUTHORED; the child set is DERIVED by inverting it.

    Slugs, never ids (fork 4). `rosters()` keys on an id's own slug component, so a slug joins no
    roster and this region leaves LIVE.md and both ledger shards byte-neutral. A bare id in a leading
    table cell would additionally ANCHOR via the extractor and rewrite the other build's `ids:` line.
    """
    mo, mc = GEN_REGIONS[2][1], GEN_REGIONS[2][2]
    out = [mo, ""]
    parents, children = build["parents"], build.get("children", [])
    if not parents and not children:
        out.append("*This build declares no parent and no build declares it as one.*")
    else:
        for label, vals in (("Parent", parents), ("Child", children)):
            if vals:
                links = ", ".join(f"[{s}](../{s}/README.md)" for s in sorted(vals))
                out.append(f"- **{label} builds:** {links}")
    out.append(mc)
    return "\n".join(out)


def render_docs(build: dict) -> str:
    """The DOCUMENT INVENTORY region: every tracked record the build holds, linked."""
    mo, mc = GEN_REGIONS[3][1], GEN_REGIONS[3][2]
    out = [mo, ""]
    if not build["docs"]:
        out.append("*This build holds no records yet.*")
    else:
        by_kind = {}
        for p in build["docs"]:
            # index 3, not 4: memory / builds / <slug> / <kind> / <file>. Bucketing on 4 keyed every
            # record by its own FILENAME, so no kind ever matched and the region rendered empty —
            # between two markers, which reads as "this build holds nothing" rather than as a fault.
            by_kind.setdefault(p.split("/")[3], []).append(p)
        for kind in RECORD_KINDS:
            if kind not in by_kind:
                continue
            out.append(f"- **`{kind}/`**")
            for p in by_kind[kind]:
                rel = p.split(f"/builds/{build['slug']}/", 1)[1]
                out.append(f"  - [{os.path.basename(p)}]({rel})")
    out.append(mc)
    return "\n".join(out)


REGION_RENDERERS = {
    "build-index": render_region,
    "build-order": render_order,
    "build-edges": render_edges,
    "build-docs": render_docs,
}


# A period ends the sentence only when whitespace or end-of-line follows it. A dot INSIDE the claim
# — `notes.md`, `(see AGENTS.md)` — is content. The first cut used `[^.]*` and stopped at the first
# dot, deleting `Records live under `spec/` and `notes.` mid-token and writing the fragment back as
# prose: the exact corruption this unit exists to prevent, one class narrower than the line-scoped
# removal the review had already rejected.
RECORDS_SENTENCE = re.compile(r"Records live under (?:[^.]|\.(?!\s|$))*\.[ ]?")
RECORDS_ANCHOR = "Records live under"


def strip_records_sentence(readme_text: str, readme: str) -> str:
    """Remove the AUTHORED folder-claim sentence from the body, OUTSIDE the marker pair.

    SENTENCE-scoped, never line-scoped: measured over the corpus, in 17 of 17 carriers the sentence
    ENDS mid-line and the next sentence begins on the same line, so deleting the LINE destroys
    unrelated prose in every file.

    FENCE-AWARE, because a README documenting this very migration quotes the retired boilerplate
    inside a code block — and the first cut rewrote that block. Unit 5 of this same build added the
    fence reader precisely because a scanner that ignores fences is wrong by construction; the writer
    has no excuse the reader did not.

    THE WHOLE DOCUMENT outside the marked slice is in scope, not merely the text above it. Bounding
    the scan at the opening marker left an authored claim below the close marker neither removed nor
    refused, so the file shipped two contradicting sentences and `--check` was a stable fixed point
    on that state.

    TWO REFUSALS, not one. More than one match is a refusal, as before. And a line carrying the
    anchor that the SENTENCE pattern does not match is also a refusal — a claim wrapped across lines
    is exactly the case where the anchor is not identifying what it was reasoned about, and silently
    leaving it produces the same two-answers state by a different route.
    """
    lines = readme_text.split("\n")
    opens = [i for i, l in enumerate(lines) if (l[:-1] if l.endswith(CR) else l) == MARK_OPEN]
    closes = [i for i, l in enumerate(lines) if (l[:-1] if l.endswith(CR) else l) == MARK_CLOSE]
    inside = range(opens[0], closes[0] + 1) if opens and closes and closes[0] >= opens[0] else range(0)
    unfenced_no = {n for n, line in unfenced_lines(readme_text) if line is not None}
    # FRONT MATTER IS NOT PROSE and is never edited here. `parse_front_matter` has already proved the
    # block opens at line 1 and closes, so the index is available — and a key whose VALUE carries the
    # anchor is legal input (the parser accepts arbitrary keys). Editing there would blank a
    # structured value silently, and `--check` would then agree with the blanked file forever. A
    # match inside the block is a refusal instead, because it means the anchor found something this
    # remover was never reasoned about.
    fm_end = 0
    if lines and lines[0].rstrip("\r") == "---":
        for i, l in enumerate(lines[1:], start=1):
            if l.rstrip("\r") == "---":
                fm_end = i
                break

    hits, anchored = [], []
    for i, line in enumerate(lines):
        if i <= fm_end and fm_end:
            if RECORDS_ANCHOR in line:
                raise Problem(f"{readme}:{i + 1}: the folder-claim anchor appears inside the front "
                              f"matter, which this remover never edits — a structured value is not "
                              f"prose, and blanking one silently is not a repair")
            continue
        if i in inside or (i + 1) not in unfenced_no:
            continue
        if RECORDS_SENTENCE.search(line):
            hits.append(i)
        elif RECORDS_ANCHOR in line:
            anchored.append(i)
    if anchored:
        where = ", ".join(str(i + 1) for i in anchored)
        raise Problem(f"{readme}: line(s) {where} carry the folder-claim anchor but no complete "
                      f"sentence — a claim wrapped across lines is not identifying what this remover "
                      f"was reasoned about, so nothing is removed")
    if not hits:
        return readme_text
    if len(hits) > 1:
        where = ", ".join(str(i + 1) for i in hits)
        raise Problem(f"{readme}: the folder-claim sentence appears {len(hits)} times outside the "
                      f"generated region, at lines {where} — the anchor is not identifying one "
                      f"sentence, so nothing is removed")
    i = hits[0]
    rest = RECORDS_SENTENCE.sub("", lines[i], count=1)
    # Only drop the physical line when the sentence WAS the whole of it; otherwise the surviving
    # text stays exactly where the author put it.
    if rest.strip():
        lines[i] = rest
    else:
        del lines[i]
    return "\n".join(lines)


def apply_front_matter_ids(readme_text: str, roster: list, readme: str) -> str:
    """Rewrite the front matter's `ids:` line from the roster, in place.

    Bounded exactly like `apply_region`: only the ONE line whose key is `ids` inside the front-matter
    block is touched, and the block ends at the first closing `---`. `parse_front_matter` has already
    proved the block opens at line 1 and closes, so this walk cannot run away; it still refuses
    rather than guessing if the key is absent, because writing a key that was never there would make
    this function a scaffolder, which it is not.
    """
    lines = readme_text.split("\n")
    want = ("ids: " + " ".join(roster)).rstrip()
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            break
        if line.startswith("ids:"):
            lines[i] = want
            return "\n".join(lines)
    raise Problem(f"{readme}: front matter has no 'ids:' line to rewrite")


def apply_region(readme_text: str, region: str, readme: str,
                 mark_open: str = MARK_OPEN, mark_close: str = MARK_CLOSE) -> str:
    """Replace the marked slice EXACTLY. Never a regex substitution over the whole file: this
    generator owns a region inside an AUTHORED file, and getting it wrong eats prose."""
    lines = readme_text.split("\n")
    # COLUMN 0, EXACT EQUALITY after one trailing CR — the contract the three awk readers in the
    # unattended kit already enforce. `.strip()` was permissive AND mutating: it accepted an
    # indented marker and a marker with trailing whitespace (two spaces is a Markdown hard break,
    # so an authored construct), then re-emitted the bare marker — silently rewriting a line the
    # author wrote, in a file they ran this tool over for another reason. Refusing is the only
    # reading that cannot edit prose behind the author.
    def _is(line, mark):
        # ONE trailing CR, not all of them. awk's `sub(/\r$/, "")` in the three unattended readers
        # removes exactly one, so `rstrip("\r")` would accept a line ending in two CRs that they
        # refuse — a divergence introduced by the very change that removed two others. It cannot be
        # demonstrated on an MSYS node, where the runtime strips CR before awk sees a byte, so it is
        # asserted at SOURCE level here rather than by a fixture that would pass either way.
        return (line[:-1] if line.endswith(CR) else line) == mark
    opens = [i for i, l in enumerate(lines) if _is(l, mark_open)]
    closes = [i for i, l in enumerate(lines) if _is(l, mark_close)]
    if not opens and not closes:
        # NAMES THE PAIR IT WAS CALLED WITH, not the module constants. "Preserved verbatim per named
        # pair" is impossible for a message built from the constants: it would be both unchanged and
        # wrong about a different region (TOOL-aRuledFrontispiece-1 S3a).
        raise Problem(f"{readme}: no '{mark_open}' / '{mark_close}' marker pair — the generated "
                      f"region has nowhere to go, and a README without one leaves the index silently")
    if len(opens) != 1 or len(closes) != 1:
        raise Problem(f"{readme}: expected exactly one '{mark_open}' marker pair, found "
                      f"{len(opens)} open and {len(closes)} close")
    if closes[0] < opens[0]:
        raise Problem(f"{readme}: the '{mark_close}' marker precedes its opening one")
    return "\n".join(lines[: opens[0]] + region.split("\n") + lines[closes[0] + 1 :])


def render_live(builds: list, m: str) -> str:
    live = [b for b in builds if b["status"] not in TERMINAL]
    out = [
        GEN_HEADER,
        f"# {m}/LIVE.md — builds with at least one non-terminal unit",
        "",
        "Derived, never authored: a build leaves this file when every one of its units reaches a",
        "terminal status. Nothing here is edited by hand.",
        "",
    ]
    if live:
        # A COUNT, not the list. This file is in check 7's entry-budget population and the build
        # README's region is not, so the full roster renders there and a bounded number renders here:
        # a ten-id row measured 316 chars against a 300-char cap, on a file with no slack.
        out += ["| Build | Status | Node | Opened | Streams | Ids (n) |", "|---|---|---|---|---|---|"]
        for b in live:
            fm = b["fm"]
            out.append(
                f"| [{b['slug']}](builds/{b['slug']}/README.md) | {b['status']} | {fm['node']} | "
                f"{fm['opened']} | {fm['streams']} | {len(b['roster'])} |"
            )
    else:
        out.append("*No live build.*")
    return "\n".join(out) + "\n"


def render_shards(builds: list, m: str) -> dict:
    months: dict = {}
    for b in builds:
        months.setdefault(b["fm"]["opened"][:7], []).append(b)
    out = {}
    for month, rows in months.items():
        body = [
            GEN_HEADER,
            f"# {m}/ledger/{month}.md — builds opened in {month}",
            "",
            "Frozen once the month passes: its inputs stop changing, so no rotation rule is needed.",
            "",
            "| Build | Status | Node | Streams | Ids (n) |",
            "|---|---|---|---|---|",
        ]
        for b in sorted(rows, key=lambda x: x["slug"]):
            fm = b["fm"]
            body.append(
                f"| [{b['slug']}](../builds/{b['slug']}/README.md) | {b['status']} | {fm['node']} | "
                f"{fm['streams']} | {len(b['roster'])} |"
            )
        out[f"{m}/ledger/{month}.md"] = "\n".join(body) + "\n"
    return out


def _marker_index(lines: list, mark: str):
    """The index of a marker line, or None. Same COLUMN-0, one-trailing-CR contract as apply_region."""
    for i, l in enumerate(lines):
        if (l[:-1] if l.endswith(CR) else l) == mark:
            return i
    return None


def slot_violations(readme_text: str, readme: str) -> list:
    """Authored content sitting where the slot contract forbids it (TOOL-aRuledFrontispiece-1 S4).

    TWO triggers, not one. An earlier draft of the owning spec named only the first, which would have
    passed the one README in the corpus that already carries a plan pair — the exact file the surgery
    unit exists to relocate.
    """
    lines = readme_text.split("\n")
    spans = []            # (open_index, close_index) of every registered generated region present
    for _name, mo, mc in GEN_REGIONS:
        o, c = _marker_index(lines, mo), _marker_index(lines, mc)
        if o is not None and c is not None and c > o:
            spans.append((o, c))
    if not spans:
        return []
    first_open = min(o for o, _c in spans)
    inside = {i for o, c in spans for i in range(o, c + 1)}
    out = []
    # Trigger 1 — authored prose AFTER the first generated marker, outside every generated region.
    for i, l in enumerate(lines):
        if i > first_open and i not in inside and l.strip():
            out.append((i + 1, "authored content after the first generated marker"))
    # Trigger 2 — authored prose BETWEEN the plan pair's close and the first generated open.
    pc = _marker_index(lines, PLAN_CLOSE)
    if pc is not None and pc < first_open:
        for i in range(pc + 1, first_open):
            if lines[i].strip():
                out.append((i + 1, "authored content between the plan pair and the generated region"))
    return sorted(set(out))


def insert_region(readme_text: str, mark_open: str, mark_close: str) -> str:
    """Create a missing pair at its CANONICAL slot, moving no authored byte (S1b, S8).

    Canonical means the order GEN_REGIONS declares, so the position is a property of that list and
    not of whoever edited the file last. Over a README that violates the slot sequence there is no
    well-defined 'after the prose' point, which is why this anchors on sibling REGIONS only — that is
    the branch every corpus write takes until the surgery unit lands.
    """
    lines = readme_text.split("\n")
    names = [mo for _n, mo, _mc in GEN_REGIONS]
    here = names.index(mark_open)
    for mo, mc in ((GEN_REGIONS[j][1], GEN_REGIONS[j][2]) for j in range(here - 1, -1, -1)):
        c = _marker_index(lines, mc)
        if c is not None:
            return "\n".join(lines[: c + 1] + ["", mark_open, mark_close] + lines[c + 1 :])
    for j in range(here + 1, len(GEN_REGIONS)):
        o = _marker_index(lines, GEN_REGIONS[j][1])
        if o is not None:
            return "\n".join(lines[:o] + [mark_open, mark_close, ""] + lines[o:])
    tail = lines if lines and lines[-1].strip() else lines[:-1] if lines else []
    return "\n".join(tail + ["", mark_open, mark_close, ""])


def plan(root: str, conf: dict, create_missing: bool = False) -> tuple:
    """Return (artifacts, orphans, unmanaged) — the whole render, computed without touching disk.

    `create_missing` is the ONE asymmetry between the two verbs (S7). `--write` passes true and adds
    a registered region a README lacks; `--check` passes false and stays silent about it. Both verbs
    call this function, so without the flag a create-if-missing step would fire under `--check` and
    report every un-paired README stale — which would force a corpus-wide re-render into the commit
    of every unit that registers a region, and is the outcome S1c exists to forbid.
    """
    m = conf["MEMORY_ROOT"]
    builds = collect(root, conf)
    # DERIVE the child set by inverting `parents:`. Authoring both directions would put two answers
    # to one question in two files with no gate on this bar able to reconcile them — the defect
    # TOOL-aMouldedFolio-1 recorded one relation over, when it refused a front-matter schema.
    known = {b["slug"] for b in builds}
    children = {}
    for b in builds:
        for p in b["parents"]:
            if p not in known:
                raise Problem(f"{b['readme']}: parents: names '{p}', which is not a build folder "
                              f"under {m}/builds/ — an edge to nothing is a typo, not a relation")
            children.setdefault(p, []).append(b["slug"])
    for b in builds:
        b["children"] = sorted(children.get(b["slug"], []))
    # The bindings, read ONCE for the whole render and attached per build. Each record is filed under
    # the build folder that HOUSES it, which is not always the build its ids belong to — a
    # cross-build record renders where a reader will look for it.
    try:
        tracked_all = [p for p in run("git", "ls-files", cwd=root).split("\n") if p]
        binds_all = read_bindings(root, tracked_all, conf)
    except Exception:  # noqa: BLE001 — the render must not depend on the parse succeeding
        binds_all = {}
    for b in builds:
        pre = f"{m}/builds/{b['slug']}/"
        b["records"] = [dict(rec, path=p) for p, rec in binds_all.items()
                        if p.startswith(pre) and rec["state"] in ("bound", "unbound")]
    artifacts = {}
    for b in builds:
        path = os.path.join(root, b["readme"])
        text = strip_records_sentence(read_text(path), b["readme"])
        text = apply_front_matter_ids(text, b["roster"], b["readme"])
        if create_missing:
            for _name, mo, mc in GEN_REGIONS:
                lines = text.split("\n")
                if _marker_index(lines, mo) is None and _marker_index(lines, mc) is None:
                    text = insert_region(text, mo, mc)
        for name, mo, mc in GEN_REGIONS:
            renderer = REGION_RENDERERS[name]
            lines = text.split("\n")
            # S1c's tolerance is for a NEW region a README has not adopted yet. It must NOT extend to
            # `build-index`, whose pair has always been mandatory: apply_region's "leaves the index
            # silently" refusal is the only thing standing between a build README and a hand-authored
            # status block. Measured with a live control — with the skip applied uniformly, deleting
            # four marker lines from a build README left --check, --check-format and the whole hygiene
            # gate green, while the pre-change engine refused the identical tree. The build's own
            # premise is that this file is generated and gated; a skip that covers the index region
            # defeats it in four lines.
            if name != GEN_REGIONS[0][0] and _marker_index(lines, mo) is None \
                    and _marker_index(lines, mc) is None:
                continue  # a region this README has not adopted — S1c
            text = apply_region(text, renderer(b), b["readme"], mo, mc)
        artifacts[b["readme"]] = text
    artifacts[f"{m}/LIVE.md"] = render_live(builds, m)
    artifacts.update(render_shards(builds, m))
    # Orphans: a tracked file under ledger/ that this render does not produce. The DELETABLE set is
    # bounded to the month-shard NAME; anything else is reported and left alone.
    tracked = [p for p in run("git", "ls-files", "--", f"{m}/ledger/", cwd=root).split("\n") if p]
    orphans, unmanaged = [], []
    for p in tracked:
        if p in artifacts:
            continue
        (orphans if SHARD_RE.match(os.path.basename(p)) and p.count("/") == 2 else unmanaged).append(p)
    return artifacts, sorted(orphans), sorted(unmanaged)


# -------------------------------------------------------------------------------------------- modes
def do_check(root: str, conf: dict) -> int:
    artifacts, orphans, unmanaged = plan(root, conf)
    bad = []
    for rel, want in sorted(artifacts.items()):
        path = os.path.join(root, rel)
        if not os.path.isfile(path):
            bad.append(f"{rel} (missing — never rendered)")
        elif read_text(path) != want:
            bad.append(f"{rel} (stale — differs from a fresh render)")
    for p in orphans:
        bad.append(f"{p} (orphaned ledger shard — no build opened in that month; --write deletes it)")
    for p in unmanaged:
        bad.append(f"{p} (unmanaged file under ledger/ — not a month shard; --write LEAVES IT ALONE)")
    if bad:
        print(f"build-index DRIFT — run: python {kit_rel()}/gen_build_index.py --write")
        for line in bad:
            print("    " + line)
        return 1
    print(f"build-index: clean ({len(artifacts)} artifact(s))")
    return 0


def do_check_format(root: str, conf: dict) -> int:
    """The SLOT CONTRACT verb — deliberately NOT reachable from plan(), --write or --check (S1a).

    Build READMEs violate the sequence at this unit's base, so a refusal on the render path would red
    hygiene check 9 across the corpus on this unit's own commit. The leg at the last build position
    is what makes this binding; the surgery unit before it is what makes it pass.
    """
    m = conf["MEMORY_ROOT"]
    tracked = [p for p in run("git", "ls-files", "--", f"{m}/builds/", cwd=root).split("\n")
               if p.endswith("/README.md")]
    bad = []
    for rel in sorted(tracked):
        for line, why in slot_violations(read_text(os.path.join(root, rel)), rel):
            bad.append(f"    {rel}:{line} — {why}")
    if bad:
        print("build-index FORMAT — authored content outside the slot contract:")
        for line in bad:
            print(line)
        return 1
    print(f"build-index: slot contract clean ({len(tracked)} build README(s))")
    return 0


def do_write(root: str, conf: dict) -> int:
    artifacts, orphans, unmanaged = plan(root, conf, create_missing=True)
    for rel, text in sorted(artifacts.items()):
        write_text(os.path.join(root, rel), text)
    for p in orphans:
        os.remove(os.path.join(root, p))
        print(f"build-index: removed orphaned shard {p}")
    for p in unmanaged:
        print(f"build-index: WARNING unmanaged file under ledger/ left in place: {p}")
    print(f"build-index: wrote {len(artifacts)} artifact(s)")
    return 0


# ----------------------------------------------------------------------------------------- selftest
def _fixture(tmp: str, *, marker=True, readme=True, status_key=None, spec_status="INPROGRESS"):
    run("git", "init", "-q", ".", cwd=tmp)
    run("git", "config", "user.email", "t@t.test", cwd=tmp)
    run("git", "config", "user.name", "t", cwd=tmp)
    write_text(os.path.join(tmp, ".memory-tree.conf"),
               'MEMORY_ROOT=memory\nDISCIPLINES="arch"\nFAMILIES="arch:ARCH"\n')
    d = os.path.join(tmp, "memory", "builds", "tOne", "spec")
    os.makedirs(d, exist_ok=True)
    if spec_status:
        write_text(os.path.join(d, "2026-08-01-spec-tOne-1.md"),
                   "# ARCH-tOne-1 — a unit\n\n**Status:** " + spec_status +
                   " · rev-1 · 2026-08-01 · node a · Tier-2 · base 0123abcd\n")
    else:
        write_text(os.path.join(d, "legacy-note.md"), "# no header here\n")
    if readme:
        fm = ["---", "slug: tOne", "node: a", "opened: 2026-08-01", "streams: arch",
              "roster: ARCH", "ids: ARCH-tOne-1"]
        if status_key:
            fm.append(f"status: {status_key}")
        fm.append("---")
        body = ["", "# tOne", ""]
        if marker:
            body += [MARK_OPEN, MARK_CLOSE]
        else:
            body += [MARK_OPEN]
        write_text(os.path.join(tmp, "memory", "builds", "tOne", "README.md"), "\n".join(fm + body) + "\n")
    run("git", "add", "-A", cwd=tmp)
    run("git", "commit", "-q", "-m", "f", "--no-verify", cwd=tmp)
    return load_conf(tmp)


def do_selftest() -> int:
    fails = []

    def arm(label, want, fn):
        try:
            got = fn()
        except Problem as exc:
            got = str(exc)
        except Exception as exc:  # noqa: BLE001 — a traceback here IS the finding
            got = f"UNEXPECTED {type(exc).__name__}: {exc}"
        if want in str(got):
            print(f"arm ok    {label}")
        else:
            fails.append(label)
            print(f"arm FAIL  {label} — expected to see: {want}\n      got: {got}")

    with tempfile.TemporaryDirectory() as base:
        # AC5 — a build leaves LIVE.md when its units go terminal, with nothing edited by hand.
        t = os.path.join(base, "live"); os.makedirs(t)
        conf = _fixture(t, spec_status="INPROGRESS")
        arm("live build appears in LIVE.md", "| [tOne](builds/tOne/README.md) | INPROGRESS",
            lambda: plan(t, conf)[0]["memory/LIVE.md"])
        t2 = os.path.join(base, "closed"); os.makedirs(t2)
        conf2 = _fixture(t2, spec_status="CLOSED")
        arm("terminal build leaves LIVE.md", "*No live build.*",
            lambda: plan(t2, conf2)[0]["memory/LIVE.md"])
        arm("terminal build still appears in its month shard", "| [tOne](../builds/tOne/README.md) | CLOSED",
            lambda: plan(t2, conf2)[0]["memory/ledger/2026-08.md"])

        # AC2 — an unpaired marker is a NAMED error, not a silent departure.
        t3 = os.path.join(base, "nomark"); os.makedirs(t3)
        conf3 = _fixture(t3, marker=False)
        # The message now NAMES the pair. With four registered regions, "expected exactly one marker
        # pair" was no longer actionable — an operator could not tell which region was malformed.
        arm("unpaired marker is named",
            "expected exactly one '<!-- gen:build-index -->' marker pair, found 1 open and 0 close",
            lambda: plan(t3, conf3))

        # The derived roster. Each arm names one branch of `rosters()`. (The owning spec is
        # deliberately NOT cited by id: a drift signal counts a non-terminal spec id appearing in
        # product source, and it sits at its pin.)
        def _roster_tree(name, extra=None, ids_line=None):
            """A fixture whose spec defines ARCH-tOne-1, plus whatever `extra` writes."""
            d = os.path.join(base, name); os.makedirs(d)
            c = _fixture(d, spec_status="INPROGRESS")
            if ids_line is not None:
                p = os.path.join(d, "memory", "builds", "tOne", "README.md")
                write_text(p, read_text(p).replace("ids: ARCH-tOne-1", ids_line))
            for rel, text in (extra or {}).items():
                full = os.path.join(d, rel.replace("/", os.sep))
                os.makedirs(os.path.dirname(full), exist_ok=True)
                write_text(full, text)
            run("git", "add", "-A", cwd=d)
            run("git", "commit", "-q", "-m", "r", "--no-verify", cwd=d)
            return d, c

        d1, c1 = _roster_tree("rosterbase", {"memory/DECISIONS.md": "- ARCH-tOne-4 · a decision\n"})
        arm("the roster is DERIVED, not read from front matter", "ids ARCH-tOne-1 ARCH-tOne-4",
            lambda: plan(d1, c1)[0]["memory/builds/tOne/README.md"])
        arm("the roster sorts by NUMERIC sequence, not lexically",
            "ARCH-tOne-2 ARCH-tOne-10",
            lambda: plan(*_roster_tree("rostersort",
                                       {"memory/DECISIONS.md": "- ARCH-tOne-10 · ten\n- ARCH-tOne-2 · two\n"}))[0]
            ["memory/builds/tOne/README.md"])
        # SELF-REFERENCE: the field must never be an input to itself, or a wrong value survives every
        # regeneration and every gate agrees, because a fresh render reproduces it exactly.
        d3, c3 = _roster_tree("rosterself", {"memory/DECISIONS.md": "- ARCH-tOne-4 · a decision\n"},
                              ids_line="ids: ARCH-tOne-1 ARCH-tOne-99")
        arm("an id present ONLY in the build's own front matter is dropped",
            "ids: ARCH-tOne-1 ARCH-tOne-4\n",
            lambda: plan(d3, c3)[0]["memory/builds/tOne/README.md"])
        # A revision-suffixed anchor amends a decision; it is not an id of its own. Admitting them
        # multiplied one real build's roster from 8 to 38.
        d4, c4 = _roster_tree("rosterrev", {"memory/DECISIONS.md": "- ARCH-tOne-4b · an amendment\n"})
        arm("a revision-suffixed anchor never joins a roster", "ids ARCH-tOne-1<",
            lambda: plan(d4, c4)[0]["memory/builds/tOne/README.md"].replace("\n", "<"))
        # The generated artifacts are rendered FROM the roster, so reading them is self-reference one
        # hop out. LIVE.md carries a COUNT for the same reason the region carries the list: only one
        # of the two files is inside check 7's entry budget.
        d5, c5 = _roster_tree("rosterexcl", {"memory/LIVE.md": "ARCH-tOne-77\n",
                                             "memory/ledger/2026-08.md": "ARCH-tOne-88\n"})
        arm("an id present only in a GENERATED artifact never joins a roster", "ids ARCH-tOne-1<",
            lambda: plan(d5, c5)[0]["memory/builds/tOne/README.md"].replace("\n", "<"))
        arm("the capped artifacts carry a COUNT, never the id list", "| arch | 2 |",
            lambda: plan(d1, c1)[0]["memory/LIVE.md"])

        # ---- the folder-claim sentence. These are FIXTURE arms on purpose: once the corpus is
        # ---- migrated the sentence is gone from it, so a control run against the live tree has
        # ---- nothing left to catch and passes whatever the remover does.
        def _rec(tmp, body):
            c = _fixture(tmp, spec_status="INPROGRESS")
            p = os.path.join(tmp, "memory", "builds", "tOne", "README.md")
            t = read_text(p)
            write_text(p, t.replace("# tOne\n", "# tOne\n\n" + body + "\n"))
            run("git", "add", "-A", cwd=tmp)
            run("git", "commit", "-q", "-m", "r", "--no-verify", cwd=tmp)
            return c

        ta = os.path.join(base, "recsurv"); os.makedirs(ta)
        ca = _rec(ta, "Records live under `spec/`. The table below is\nGENERATED from the header.")
        arm("the text following the sentence SURVIVES the removal", "The table below is",
            lambda: plan(ta, ca)[0]["memory/builds/tOne/README.md"])
        arm("the authored sentence leaves the body", "1",
            lambda: str(plan(ta, ca)[0]["memory/builds/tOne/README.md"].count("Records live under")))
        tb = os.path.join(base, "recwhole"); os.makedirs(tb)
        cb = _rec(tb, "Records live under `spec/`.")
        # ASSERT THE SHAPE, NOT A COUNT. The count `1` is satisfied by the DERIVED sentence alone, so
        # it holds whether the whole-line branch deletes the line or leaves it empty — collapsing
        # `del lines[i]` to `lines[i] = rest` passed the entire selftest while changing the render.
        # The residual blank line is the only observable difference, so that is what is asserted.
        # The sentence line sat between two blanks, so deleting it leaves exactly those two and the
        # marker follows. Collapsing the branch to `lines[i] = rest` leaves a THIRD blank — the only
        # observable difference, and the one a count could never see.
        arm("a line that was ONLY the sentence is removed entirely, leaving no extra blank",
            "# tOne" + chr(10) * 3 + MARK_OPEN,
            lambda: plan(tb, cb)[0]["memory/builds/tOne/README.md"])
        # and the mid-line case keeps ONE space where the sentence was, which pins the `[ ]?`
        tb2 = os.path.join(base, "recmid"); os.makedirs(tb2)
        cb2 = _rec(tb2, "Prefix text. Records live under `spec/`. Suffix text.")
        arm("removing a mid-line sentence leaves exactly one space, not two",
            "Prefix text. Suffix text.",
            lambda: plan(tb2, cb2)[0]["memory/builds/tOne/README.md"])
        # [6] front matter is structured input, not prose: a key whose value carries the anchor
        # was silently BLANKED, and --check then agreed with the blanked file forever.
        tfm = os.path.join(base, "recfm"); os.makedirs(tfm)
        cfm = _fixture(tfm, spec_status="INPROGRESS")
        _q = os.path.join(tfm, "memory", "builds", "tOne", "README.md")
        write_text(_q, read_text(_q).replace("ids: ARCH-tOne-1",
                    "ids: ARCH-tOne-1" + chr(10) + "notes: Records live under `spec/`."))
        run("git", "add", "-A", cwd=tfm); run("git", "commit", "-q", "-m", "f", "--no-verify", cwd=tfm)
        arm("the anchor inside FRONT MATTER is refused, never blanked",
            "a structured value is not prose", lambda: plan(tfm, cfm))
        tc = os.path.join(base, "rectwice"); os.makedirs(tc)
        cc = _rec(tc, "Records live under `spec/`. one\n\nRecords live under `build/`. two")
        arm("the sentence appearing twice outside the region is a REFUSAL",
            "is not identifying one sentence", lambda: plan(tc, cc))
        arm("the derived sentence names only the folders that exist", "Records live under `spec/`.",
            lambda: plan(ta, ca)[0]["memory/builds/tOne/README.md"])

        # ---- the four shapes the closing review reproduced against the first cut. Each corrupted or
        # ---- silently skipped an authored README, and each is now a fixture rather than a promise.
        td = os.path.join(base, "recdot"); os.makedirs(td)
        cd_ = _rec(td, "Records live under `spec/` and `notes.md`. The table below is\nGENERATED.")
        # The surviving line must be EXACTLY the next sentence. Asserting merely that "The table
        # below is" appears does NOT discriminate: the truncating pattern leaves `md`. The table
        # below is`, which contains it — both first-cut arms passed over the corruption they were
        # written to catch, and only the negative control exposed them.
        arm("a dot INSIDE the claim does not truncate the match, leaving no fragment",
            chr(10) + "The table below is" + chr(10),
            lambda: plan(td, cd_)[0]["memory/builds/tOne/README.md"])
        te = os.path.join(base, "recfence"); os.makedirs(te)
        ce = _rec(te, "The old text read:\n\n```\nRecords live under `spec/`, `build/`. Quoted.\n```\n\nNow derived.")
        arm("a fenced QUOTE of the sentence is left untouched", "Records live under `spec/`, `build/`. Quoted.",
            lambda: plan(te, ce)[0]["memory/builds/tOne/README.md"])
        tf = os.path.join(base, "recbelow"); os.makedirs(tf)
        cf = _rec(tf, "intro")
        _p = os.path.join(tf, "memory", "builds", "tOne", "README.md")
        write_text(_p, read_text(_p) + "\n### later\n\nRecords live under `build/`. Read in order.\n")
        run("git", "add", "-A", cwd=tf); run("git", "commit", "-q", "-m", "b", "--no-verify", cwd=tf)
        arm("a claim BELOW the marker pair is removed too, not ignored", "1",
            lambda: str(plan(tf, cf)[0]["memory/builds/tOne/README.md"].count("Records live under")))
        tg = os.path.join(base, "recwrap"); os.makedirs(tg)
        cg = _rec(tg, "Records live under `spec/`, `build/` and\n`reviews/`. The table below is GENERATED.")
        arm("a claim WRAPPED across lines is a named refusal, not a silent skip",
            "no complete sentence", lambda: plan(tg, cg))

        # AC4 — an absent README is a named error on BOTH modes, never a traceback.
        t4 = os.path.join(base, "noreadme"); os.makedirs(t4)
        conf4 = _fixture(t4, readme=False)
        arm("absent README is named, not a traceback", "no tracked README.md",
            lambda: plan(t4, conf4))

        # AC8 — the status: fallback, both arms.
        t5 = os.path.join(base, "noheader"); os.makedirs(t5)
        conf5 = _fixture(t5, spec_status=None)
        arm("no parseable header and no status: is named", "declare it explicitly with a 'status:'",
            lambda: plan(t5, conf5))
        t6 = os.path.join(base, "declared"); os.makedirs(t6)
        conf6 = _fixture(t6, spec_status=None, status_key="SPECCED")
        arm("declared status is used when nothing is derivable", "| SPECCED |",
            lambda: plan(t6, conf6)[0]["memory/LIVE.md"])
        t7 = os.path.join(base, "conflict"); os.makedirs(t7)
        conf7 = _fixture(t7, spec_status="OPEN", status_key="CLOSED")
        arm("declared status alongside a derivable one is a conflict", "two answers to one",
            lambda: plan(t7, conf7))

        # AC3 — orphan handling, and its BOUND.
        t8 = os.path.join(base, "orphan"); os.makedirs(t8)
        conf8 = _fixture(t8, spec_status="OPEN")
        write_text(os.path.join(t8, "memory", "ledger", "1999-01.md"), "stale\n")
        write_text(os.path.join(t8, "memory", "ledger", "notes.md"), "authored\n")
        run("git", "add", "-A", cwd=t8)
        run("git", "commit", "-q", "-m", "orphans", "--no-verify", cwd=t8)
        arm("an orphaned month shard is reported", "memory/ledger/1999-01.md",
            lambda: str(plan(t8, conf8)[1]))
        arm("a non-shard file under ledger/ is NOT deletable", "memory/ledger/notes.md",
            lambda: str(plan(t8, conf8)[2]))
        do_write(t8, conf8)
        arm("--write removed the orphan", "False",
            lambda: str(os.path.exists(os.path.join(t8, "memory", "ledger", "1999-01.md"))))
        arm("--write kept the unmanaged file", "True",
            lambda: str(os.path.exists(os.path.join(t8, "memory", "ledger", "notes.md"))))

        # front matter: line 1 only, keys at column 0.
        t9 = os.path.join(base, "fm"); os.makedirs(t9)
        conf9 = _fixture(t9, spec_status="OPEN")
        rd = os.path.join(t9, "memory", "builds", "tOne", "README.md")
        write_text(rd, "# a heading first\n\n" + read_text(rd))
        arm("front matter must open at line 1", "line 1 must be '---'", lambda: plan(t9, conf9))
        t10 = os.path.join(base, "indent"); os.makedirs(t10)
        conf10 = _fixture(t10, spec_status="OPEN")
        rd10 = os.path.join(t10, "memory", "builds", "tOne", "README.md")
        write_text(rd10, read_text(rd10).replace("node: a", "  node: a"))
        arm("an indented front-matter key is named", "keys live at COLUMN 0", lambda: plan(t10, conf10))

        # --write then --check is a fixed point. Without this a renderer that emits CRLF, or a
        # comparison that normalises differently from the writer, is green on the run that wrote it
        # and red forever after.
        t11 = os.path.join(base, "roundtrip"); os.makedirs(t11)
        conf11 = _fixture(t11, spec_status="OPEN")
        do_write(t11, conf11)
        arm("write then check is a fixed point", "0", lambda: str(do_check(t11, conf11)))

        # ---- TOOL-aRuledFrontispiece-1: the slot contract, region creation, and the ASYMMETRY.
        # A fixture whose README carries ONLY the build-index pair: the other three are absent.
        t12 = os.path.join(base, "regions"); os.makedirs(t12)
        conf12 = _fixture(t12, spec_status="OPEN")
        rd12 = os.path.join(t12, "memory", "builds", "tOne", "README.md")

        # S1c — the ASYMMETRY. --check must be SILENT about the three absent pairs.
        #
        # ORDER IS THE WHOLE ARM. This ran AFTER do_write, which had just created the three pairs, so
        # there was no absent pair left to be silent about and the arm could not fail: mutation-proved
        # by patching do_check to pass create_missing=True — the exact regression it claims to catch —
        # and watching the suite still report PASS. It runs BEFORE the write now, on a fixture that
        # genuinely lacks the pairs, and asserts the render directly rather than an exit code.
        # THE ARM MUST RUN THROUGH do_check, not through plan(). Two earlier spellings did not, and
        # both were mutation-proved useless: one ran after do_write so no pair was absent, and one
        # called plan() directly so patching do_check — the site that actually carries the defect —
        # left the suite green. The fixture is rendered FIRST so the build-index region is fresh, then
        # the three other pairs are removed. Now the only thing that can make do_check report stale is
        # create_missing leaking into it, which is exactly S1c.
        rd12 = os.path.join(t12, "memory", "builds", "tOne", "README.md")
        do_write(t12, conf12)
        # WHOLE regions, markers and body together. Stripping only the marker lines orphans the
        # rendered body as loose authored text, which makes the fixture genuinely non-conforming and
        # reds a later arm for a reason that has nothing to do with what this one tests.
        _ls = read_text(rd12).split("\n")
        for _i in (3, 2, 1):
            _o, _c = _marker_index(_ls, GEN_REGIONS[_i][1]), _marker_index(_ls, GEN_REGIONS[_i][2])
            if _o is not None and _c is not None:
                _ls = _ls[:_o] + _ls[_c + 1:]
        write_text(rd12, "\n".join(_ls))
        arm("check does not CREATE an absent pair", "0", lambda: str(do_check(t12, conf12)))
        arm("the three pairs really are absent for that arm", "3",
            lambda: str(sum(GEN_REGIONS[i][1] not in read_text(rd12) for i in (1, 2, 3))))
        do_write(t12, conf12)
        arm("write restores them", "0", lambda: str(
            sum(GEN_REGIONS[i][1] not in read_text(rd12) for i in (1, 2, 3))))
        arm("write CREATED the three absent pairs", "3",
            lambda: str(sum(GEN_REGIONS[i][1] in read_text(rd12) for i in (1, 2, 3))))
        arm("created pairs land in CANONICAL order", "True", lambda: str(
            read_text(rd12).index(GEN_REGIONS[1][1]) < read_text(rd12).index(GEN_REGIONS[2][1])
            < read_text(rd12).index(GEN_REGIONS[3][1])))

        # S8 — over a README that VIOLATES the sequence, the pair still lands and no authored byte
        # moves. This is the branch the whole corpus takes until the surgery unit lands, so it is the
        # common case rather than an edge one.
        t13 = os.path.join(base, "violator"); os.makedirs(t13)
        conf13 = _fixture(t13, spec_status="OPEN")
        rd13 = os.path.join(t13, "memory", "builds", "tOne", "README.md")
        write_text(rd13, read_text(rd13) + "\n## Afterword\n\nauthored prose below the region.\n")
        do_write(t13, conf13)
        arm("a violating README keeps its authored tail", "authored prose below the region.",
            lambda: read_text(rd13))
        arm("a violating README still gains its pairs", "True",
            lambda: str(all(GEN_REGIONS[i][1] in read_text(rd13) for i in (1, 2, 3))))

        # S4 — BOTH triggers. The second one is the arm an earlier draft of the spec had no rule for,
        # and it is the one the single corpus README carrying a plan pair actually trips.
        arm("slot walk names prose after the first generated marker",
            "authored content after the first generated marker",
            lambda: str(slot_violations(read_text(rd13), "x")))
        t14 = os.path.join(base, "planprose"); os.makedirs(t14)
        conf14 = _fixture(t14, spec_status="OPEN")
        rd14 = os.path.join(t14, "memory", "builds", "tOne", "README.md")
        write_text(rd14, read_text(rd14).replace(
            MARK_OPEN, PLAN_OPEN + "\n| # | unit |\n" + PLAN_CLOSE + "\n\nstray prose.\n\n" + MARK_OPEN))
        arm("slot walk names prose between the plan pair and the region",
            "authored content between the plan pair and the generated region",
            lambda: str(slot_violations(read_text(rd14), "x")))
        # S2 — the generator NEVER writes between the plan markers.
        do_write(t14, conf14)
        arm("the authored plan region survives a write verbatim", "| # | unit |",
            lambda: read_text(rd14))

        # A conforming README yields NO violations — the arm that keeps the walk from being vacuous.
        arm("a conforming README trips no trigger", "[]",
            lambda: str(slot_violations(read_text(rd12), "x")))

        # S11 — the document inventory NAMES a record. This arm exists because the first cut bucketed
        # each record by its own filename rather than by its kind folder, so no kind ever matched and
        # the region rendered EMPTY between its two markers — which reads as "this build holds no
        # records", not as a fault. A region whose population selector silently matches nothing is the
        # vacuous-selector class, and only a positive arm catches it.
        arm("the document inventory names a real record", "2026-08-01-spec-tOne-1.md",
            lambda: render_docs([b for b in collect(t12, conf12) if b["slug"] == "tOne"][0]))
        arm("the document inventory buckets under its KIND folder", "**`spec/`**",
            lambda: render_docs([b for b in collect(t12, conf12) if b["slug"] == "tOne"][0]))

        # S10 — an edge to a build that does not exist is a typo, not a relation.
        t15 = os.path.join(base, "badedge"); os.makedirs(t15)
        conf15 = _fixture(t15, spec_status="OPEN")
        rd15 = os.path.join(t15, "memory", "builds", "tOne", "README.md")
        write_text(rd15, read_text(rd15).replace("ids: ARCH-tOne-1", "ids: ARCH-tOne-1\nparents: tGhost"))
        run("git", "add", "-A", cwd=t15)
        arm("an edge to a nonexistent build is named", "which is not a build folder",
            lambda: plan(t15, conf15))
        # ---- the record->spec binding parser.
        # Every arm is a POSITIVE assertion on a classification, because the failure mode of a
        # head-scan is silence: a boundary set one line short reports "absent" for a conformant
        # record and nothing anywhere says so.
        tb = os.path.join(base, "bind"); os.makedirs(tb)
        bconf = {"MEMORY_ROOT": "memory", "FAMILIES": "tooling:TOOL playbook:PLAY"}

        def _rec(rel, body):
            p = os.path.join(tb, rel)
            os.makedirs(os.path.dirname(p), exist_ok=True)
            write_text(p, body)
            return rel

        def _bind(rel):
            return read_bindings(tb, [rel], bconf)[rel]

        r1 = _rec("memory/builds/tOne/reviews/r.md",
                  "# t\n\n**Serves:** spec-audit TOOL-tOne-1 TOOL-tOne-2\n")
        arm("binding parses kind + ids", "bound", lambda: _bind(r1)["state"])
        arm("binding keeps both ids", "['TOOL-tOne-1', 'TOOL-tOne-2']", lambda: str(_bind(r1)["ids"]))

        r2 = _rec("memory/builds/tOne/reviews/r2.md",
                  "# t\n\n**Serves:** none — the build shipped before any spec existed\n")
        arm("none form with a reason is unbound", "unbound", lambda: _bind(r2)["state"])

        r3 = _rec("memory/builds/tOne/reviews/r3.md", "# t\n\n**Serves:** none\n")
        arm("bare none with no reason is malformed", "malformed", lambda: _bind(r3)["state"])

        r4 = _rec("memory/builds/tOne/reviews/r4.md", "# t\n\n**Serves:** postmortem TOOL-tOne-1\n")
        arm("an unknown kind token is malformed", "is not one of", lambda: _bind(r4)["why"])

        r5 = _rec("memory/builds/tOne/build/r5.md", "# t\n\n**Serves:** journal TOOL-tOne-2..4\n")
        arm("a range EXPANDS at authoring time", "['TOOL-tOne-2', 'TOOL-tOne-3', 'TOOL-tOne-4']",
            lambda: str(_bind(r5)["ids"]))

        r6 = _rec("memory/builds/tOne/reviews/r6.md",
                  "\n" * 13 + "**Serves:** spec-audit TOOL-tOne-1\n")
        arm("a Serves line past the head window is not read", "absent", lambda: _bind(r6)["state"])

        r7 = _rec("memory/builds/tOne/reviews/r7.md",
                  "# t\n\n```\n**Serves:** spec-audit TOOL-tOne-1\n```\n")
        arm("a FENCED example never parses as a binding", "absent", lambda: _bind(r7)["state"])

        r8 = _rec("memory/builds/tOne/build/r8.sh",
                  "#!/bin/sh\n# **Serves:** journal TOOL-tOne-1\n")
        arm("a non-markdown record binds through a comment marker", "bound", lambda: _bind(r8)["state"])

        r9 = _rec("memory/builds/tOne/reviews/r9.md",
                  "# t\n\n**Serves:** diff-review TOOL-tOne-1@rev-3 PLAY-tTwo-9\n")
        arm("a rev qualifier is accepted and normalised away",
            "['TOOL-tOne-1', 'PLAY-tTwo-9']", lambda: str(_bind(r9)["ids"]))
        arm("an id may reach into another build", "PLAY-tTwo-9", lambda: str(_bind(r9)["ids"]))

        r10 = _rec("memory/builds/tOne/reviews/r10.md", "# t\n\n**Serves:** journal TOOL-tOne-x\n")
        arm("a malformed id token is reported, not silently dropped", "TOOL-tOne-x",
            lambda: str(_bind(r10)["bad"]))

        r11 = _rec("memory/builds/tOne/reviews/r11.md",
                   "# t\n\n**Serves:** journal TOOL-tOne-1  <!-- inferred: single-spec build -->\n")
        arm("a trailing comment is a note, not a token", "['TOOL-tOne-1']", lambda: str(_bind(r11)["ids"]))
        arm("a trailing comment contributes no malformed token", "[]", lambda: str(_bind(r11)["bad"]))

        _rec("memory/builds/tOne/spec/s.md", "# TOOL-tOne-1 — the unit\n")
        _rec("memory/builds/tOne/spec/units/s2.md", "# PLAY-tTwo-9 — nested, any depth\n")
        arm("spec_ids resolves an H1 id at any depth under spec/", "PLAY-tTwo-9",
            lambda: str(sorted(spec_ids(tb, ["memory/builds/tOne/spec/s.md",
                                             "memory/builds/tOne/spec/units/s2.md"], bconf))))
        arm("a record is NOT a definition source", "[]",
            lambda: str(sorted(spec_ids(tb, [r1], bconf))))

        # The read-only property, asserted as an ON-DISK effect rather than an exit code: a
        # read-only verb that writes is the whole risk of that verb.
        t12 = os.path.join(base, "ro"); os.makedirs(t12)
        conf12 = _fixture(t12)
        do_write(t12, conf12)
        _before = {p: read_text(os.path.join(t12, p)) for p in
                   ("memory/LIVE.md", "memory/builds/tOne/README.md")}
        do_print_bindings(t12, conf12)
        arm("--print-bindings leaves every generated artifact byte-identical", "True",
            lambda: str(all(read_text(os.path.join(t12, p)) == v for p, v in _before.items())))

        # The S row: a BOUND record is not a finding, so nothing else in this output mentions it,
        # and check 21's filename-vs-header branch has no input without it.
        def _rows(tree, cf):
            import io as _io, contextlib as _cl
            buf = _io.StringIO()
            with _cl.redirect_stdout(buf):
                do_print_bindings(tree, cf)
            return buf.getvalue()

        t13 = os.path.join(base, "srow"); os.makedirs(t13)
        conf13 = _fixture(t13)
        p13 = os.path.join(t13, "memory/builds/tOne/reviews/2026-08-01-review-tOne-1.md")
        os.makedirs(os.path.dirname(p13), exist_ok=True)
        write_text(p13, "# r\n\n**Serves:** spec-audit ARCH-tOne-1\n")
        run("git", "add", "-A", cwd=t13)
        arm("a bound record emits an S row carrying kind and the resolved ids",
            "S\tmemory/builds/tOne/reviews/2026-08-01-review-tOne-1.md\tspec-audit\tARCH-tOne-1",
            lambda: _rows(t13, conf13))
        arm("--print-bindings still exits 0 with an S row present", "0",
            lambda: str(do_print_bindings(t13, conf13)))

        # ---- the rendered Records table and the two coverage joins.
        arm("a build with a record renders it in the Records table",
            "| [2026-08-01-review-tOne-1.md](reviews/2026-08-01-review-tOne-1.md) | spec-audit | ARCH-tOne-1 |",
            lambda: plan(t13, conf13)[0]["memory/builds/tOne/README.md"])
        arm("the derived folder sentence SURVIVES the table (nine arms depend on it)",
            "Records live under", lambda: plan(t13, conf13)[0]["memory/builds/tOne/README.md"])
        # The record above serves the build's only id, so neither join has anything to report. A
        # positive-population arm: an empty table rendering silently is the failure that matters.
        arm("a fully-covered build renders no coverage line", "True",
            lambda: str("Ids no record names:" not in
                        plan(t13, conf13)[0]["memory/builds/tOne/README.md"]))
        t14 = os.path.join(base, "gap"); os.makedirs(t14)
        conf14 = _fixture(t14)
        p14 = os.path.join(t14, "memory/builds/tOne/build/2026-08-01-build-tOne-1.md")
        os.makedirs(os.path.dirname(p14), exist_ok=True)
        write_text(p14, "# j\n\n**Serves:** journal ARCH-tOne-1\n")
        run("git", "add", "-A", cwd=t14)
        arm("a build whose only record is a journal names its id as never spec-audited",
            "Ids no `spec-audit` record has ever named: ARCH-tOne-1",
            lambda: plan(t14, conf14)[0]["memory/builds/tOne/README.md"])
        arm("...and does NOT claim the id is unnamed, which a journal did name", "True",
            lambda: str("Ids no record names:" not in
                        plan(t14, conf14)[0]["memory/builds/tOne/README.md"]))
        t15 = os.path.join(base, "norec"); os.makedirs(t15)
        conf15 = _fixture(t15)
        arm("a build with NO records renders neither the table nor a coverage line", "True",
            lambda: str("| Record | Kind | Serves |" not in
                        plan(t15, conf15)[0]["memory/builds/tOne/README.md"]))

    if fails:
        print(f"FAIL — {len(fails)} arm(s) failed")
        return 1
    print("PASS — gen_build_index: all arms held")
    return 0


def main(argv: list) -> int:
    mode = argv[1] if len(argv) > 1 else "--check"
    if mode == "--selftest":
        return do_selftest()
    if mode not in ("--check", "--write", "--check-format", "--print-bindings"):
        print("usage: gen_build_index.py [--check|--write|--check-format|--print-bindings|--selftest]")
        return 2
    try:
        root = run("git", "rev-parse", "--show-toplevel").strip()
    except Exception:  # noqa: BLE001
        print("build-index: not a git repo")
        return 2
    conf = load_conf(root)
    if mode == "--print-bindings":
        return do_print_bindings(root, conf)
    try:
        if mode == "--check-format":
            return do_check_format(root, conf)
        return do_check(root, conf) if mode == "--check" else do_write(root, conf)
    except Problem as exc:
        print(f"build-index: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
